
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[678] =
    {   0,
        0,    0,    0,    0,   82,   80,    3,    1,    2,   51,
       80,   45,   80,   80,    4,    5,   41,   37,    8,   39,
       43,   62,   63,   61,    6,    7,   79,   80,   80,   78,
       78,    3,   58,    0,   72,    0,   47,    0,    0,    0,
       53,   55,   60,   57,   59,   79,    0,   49,    0,    0,
        0,    0,   72,   73,    0,    0,    0,   10,   79,    9,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   75,
        0,   79,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,    0,   75,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   74,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   79,   79,   79,   48,
       79,   42,   79,   79,   69,   79,   79,   79,   79,   79,
       79,   52,   29,   79,   36,   79,   79,   79,   68,   79,
       79,   79,   79,   79,   44,   79,   79,   79,   19,   38,
       79,   79,   79,   79,   79,   79,   35,    0,    0,    0,

        0,    0,    0,    0,   79,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   79,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   79,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   79,   50,   79,   56,
       79,   79,    0,   25,   23,   79,   79,   79,   30,   79,
       79,   79,   79,   79,    0,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,    0,   79,   70,   64,

        0,    0,    0,    0,    0,   79,    0,    0,    0,    0,
        0,    0,    0,    0,   79,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   79,   79,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   17,   65,   79,
       79,    0,   15,   28,   79,   20,   79,   79,   79,   34,
        0,   79,   18,   79,   79,   79,   79,   79,   79,   79,
       32,    0,    0,   79,    0,   79,    0,   79,    0,    0,
        0,    0,   79,    0,    0,    0,    0,    0,    0,    0,

        0,   79,   79,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   79,    0,   79,   79,
       79,   79,    0,   79,   54,   40,   79,   46,   79,   71,
       21,    0,    0,   14,    0,   79,    0,   79,    0,    0,
        0,    0,   79,    0,    0,    0,   79,   79,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   79,    0,   31,   79,   79,   79,
        0,   33,   79,   76,    0,    0,    0,   79,   79,   67,
        0,    0,   79,   66,    0,   79,   79,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   79,
       79,    0,   16,    0,    0,    0,   22,   79,    0,    0,
       79,   79,   79,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   79,   13,    0,    0,    0,    0,   79,    0,
       79,   79,   79,    0,    0,    0,    0,    0,    0,    0,
        0,   24,    0,    0,    0,    0,   26,   27,   79,   79,
       77,    0,    0,    0,    0,   79,   79,    0,    0,    0,
        0,   79,   12,    0,    0,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   18,
       19,   20,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       21,   22,   23,    1,   24,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   25,    1,    1,    1,   26,   27,   28,
       29,   26,   30,   26,   31,   32,   26,   26,   33,   26,
       34,   26,   35,   26,   26,   26,   36,   26,   37,   38,
       39,   40,   26,   41,   42,   43,   26,   26,   44,   26,
       45,   26,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   26,   60,   26,   26,
       26,   61,   62,   63,   64,   26,   26,   65,   26,   66,
       67,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   68,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[69] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    4,    4,    4,    5,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1
    } ;

static const flex_int16_t yy_base[685] =
    {   0,
        0,   67, 1177, 1176, 1243, 1246, 1240, 1246, 1246, 1222,
       10, 1246, 1232,   15, 1246, 1246, 1246, 1226, 1246, 1223,
     1246, 1218, 1217, 1216, 1246, 1246,   21, 1209,    0, 1246,
     1184, 1230, 1246,   16, 1246,   20, 1246, 1222, 1221,   44,
     1246, 1246, 1246, 1246, 1246,   27,    5, 1246, 1182,  110,
      149, 1171,   21, 1246,    0,    0,  184, 1246,   28, 1246,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,  156,  157,  158,  159,  161,  163,  184,  193,
     1159,  187,   48,   63,   65,   67,   69,   71,   73,   75,
       77,   79,   81,   83,  143,  145,  165,  169,  171,  173,

      194, 1158,  196, 1176,  210, 1169, 1166, 1195, 1194, 1154,
     1186, 1152, 1186, 1155,    2, 1149,  190, 1155, 1179, 1145,
     1177,  204, 1183, 1143,  165,  181, 1175, 1170,    4,  222,
     1156,  241, 1154,  233,  235,  236,  238,  240,  241,  242,
      243,  244,  248,  250,  251,  252,  253,  254,  256,  257,
      258,  259,  260,  261,  262,  263,  264,  276,  278,  281,
      283,  289,  290,  291,  293,  299,  309,  310,  311,  312,
      313,  314,  334,  326, 1136,  204,  290,  298,  303,  305,
      313,  315,  319,  321,  323,  325,  346,  348,  350,  352,
      354,  356,  358,  360,  362,  364,  366,  368,  370,  372,

      374,  376,  378,  380,  382,  384,  386,  388,  390,  392,
      394,  396,  398,  400, 1135, 1152, 1167, 1145, 1142, 1170,
     1131, 1150, 1136, 1134, 1149, 1135, 1154, 1133, 1151, 1129,
     1128, 1121,  415, 1128, 1125, 1124, 1122, 1116, 1146,    2,
     1121, 1118, 1138, 1142, 1127, 1137, 1106, 1133, 1137, 1111,
     1107, 1130, 1133, 1100, 1105, 1130,  428,  429,  430,  431,
      432,  433,  434,  435,  436,  437,  438,  439,  440,  441,
      442,  443,  444,  445,  446,  447,  448,  449,  450,  451,
      452,  453,  454,  456,  457,  458,  459,  460,  461,  462,
      463,  464,  465,  466,  467,  468,  469, 1095,  445,  489,

      491,  493,  495,  497,  499,  499,  501,  503,  505,  507,
      509,  511,  513,  515,  519,  542,  521,  523,  525,  527,
      529,  531,  533,  535,  537,  539,  541,  568,  544,  546,
      548, 1113, 1099, 1094, 1093, 1122, 1110, 1089,  550, 1122,
     1123, 1086, 1086, 1117, 1113, 1089,  308, 1081, 1114,  552,
     1107, 1111, 1079, 1078, 1075, 1080, 1093, 1105, 1104, 1090,
     1109,  554, 1101, 1076, 1082, 1085,  581,  582,  583,  584,
      585,  587, 1068,  588,  589,  590,  591,  592,  593,  594,
      595,  596,  597,  598, 1067,  599,  600,  601,  602,  603,
      604,  605,  606,  607,  608,  609, 1076,  610,  611,  613,

     1060,  589,  591,  593,  595,  622,  598,  633,  635,  637,
      639,  642,  644,  646,  630,  650,  652,  654,  656,  658,
      660,  662,  664,  666,  668,  656,  673,  670, 1078, 1067,
     1074, 1093, 1065,  672, 1085, 1085, 1080, 1088, 1084, 1052,
     1058, 1056,  676, 1057, 1055, 1046, 1078, 1052, 1078, 1053,
     1049, 1044, 1038,  678,  680, 1046, 1048,  699,  707,  708,
      709, 1045,  710,  711,  712,  713,  714,  715,  716,  718,
     1044,  719,  720,  721,  722,  723,  724,  725,  726,  727,
      728, 1047, 1065,  729, 1030,  730,  706,  733,  709,  711,
      713,  715,  742,  719,  721,  723,  750,  753,  755,  757,

      759,  750,  761,  762, 1047,  764, 1031,  766, 1061, 1035,
     1060, 1027,  770, 1063, 1054, 1050, 1023, 1025, 1052, 1019,
     1038,  772,  774, 1017, 1048, 1033,  793, 1014,  801,  802,
      803,  804, 1013,  806,  807,  808,  809,  810,  811,  812,
      813, 1044, 1018,  814, 1008,  815,  791,  818,  794,  796,
      798,  800,  827,  803,  805,  807,  834,  835, 1026,  813,
     1043,  815, 1015, 1005, 1028, 1039,  817, 1009, 1000, 1000,
      835,  838,  982,  973,  836,  985,  844,  849,  865,  866,
      984,  867,  868,  869,  975, 1000, 1008,  870,  872,  873,
      849,  851,  881,  882,  858,  885,  886,  961,  864,  866,

      970,  976,  869,  975,  871,  873,  976,  983,  961,  887,
      906,  969,  901,  984,  977,  954,  902,  903,  879,    0,
      907,  908,  915,  946,  893,  948,  991,  895,  897,  902,
      960,  943,  924, 1246,  942,  968,  972,  971,  932,  908,
      935,  936,  937,  933,  913,  933,  915,  917,  923,  949,
      357,  944,  340,  326,  297,  281,  953,  954,  955,  956,
     1246,  932,  935,  282,  185,  962,  963,  939,  941,  130,
       77,  969,  970,  946,   42,  973, 1246, 1041, 1046, 1051,
     1056, 1058,   24, 1063
    } ;

static const flex_int16_t yy_def[685] =
    {   0,
      678,  678,  679,  679,  677,  677,  677,  677,  677,  677,
      680,  677,  677,  681,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  680,  677,  680,  677,  677,  681,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
       50,  677,  680,  677,  682,  683,  683,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,

      677,  677,  677,  677,  683,  683,  683,   57,   57,  683,
       57,  683,   57,  683,   57,  683,  683,  683,   57,  683,
       57,  683,   57,  683,  683,  683,   57,  683,   57,  683,
      677,   57,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,

      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,   57,  683,  683,  683,
      683,  683,  683,  683,  683,  683,  683,  683,  683,  683,
      683,  683,  683,  683,  683,  683,  683,  683,   57,  683,
      683,  683,  683,   57,  683,  683,  683,  683,   57,  683,
      683,  683,   57,  683,  683,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,

      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  683,  683,  683,  683,  683,  683,  677,   57,
       57,  683,  683,   57,  683,  683,  683,  683,   57,  677,
      683,   57,  683,  683,  683,  683,  683,   57,   57,  683,
       57,  677,   57,  683,  683,  677,  677,  677,  677,  677,
      677,  677,  683,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  683,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  683,  677,  677,  677,

      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  683,
      683,   57,  683,  677,  683,  683,  683,   57,   57,  683,
      683,  683,  677,  683,  683,  683,   57,  683,   57,  683,
      683,  683,  683,  677,  677,  683,  677,  677,  677,  677,
      677,  683,  677,  677,  677,  677,  677,  677,  677,  677,
      683,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  683,   57,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,

      677,  677,  677,  677,  677,  677,  683,  677,   57,  683,
       57,  683,  677,   57,  683,  683,  683,  683,   57,  683,
      683,  677,  677,  683,  677,  683,  677,  683,  677,  677,
      677,  677,  683,  677,  677,  677,  677,  677,  677,  677,
      677,   57,  683,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
       57,  677,  683,  683,  683,   57,  677,  683,  683,  683,
      677,  677,  677,  683,  677,  683,  677,  677,  677,  677,
      683,  677,  677,  677,  683,   57,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,

      683,  683,  677,  683,  677,  677,  677,  683,  683,  677,
      677,  683,  677,   57,  683,  677,  677,  677,  677,  684,
      677,  677,  677,  677,  677,  683,  684,  677,  677,  677,
      677,  683,  677,  677,  683,  683,   57,  677,  677,  677,
      677,  677,  677,  677,  677,  683,  677,  677,  677,  677,
      683,  677,  683,   57,  683,  677,  677,  677,  677,  677,
      677,  677,  677,  683,  683,  677,  677,  677,  677,  683,
      683,  677,  677,  677,  683,  677,    0,  677,  677,  677,
      677,  677,  677,  677
    } ;

static const flex_int16_t yy_nxt[1315] =
    {   0,
      677,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   35,   21,   22,   23,   24,
       25,   35,   26,   27,   28,   53,   35,   46,  677,  677,
      167,   36,  146,  147,  168,  677,   39,   36,  281,  677,
      677,   36,   36,  677,   46,  677,  282,   49,   50,   51,
       46,   46,   54,   56,   57,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   29,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   40,   21,   22,   23,   24,   25,   47,   26,
       27,   28,   55,   55,   47,   47,  105,   57,  676,   83,

       84,   85,   86,   87,   88,   89,   90,   91,   92,   93,
       94,  106,   57,  107,   57,   56,  108,   56,  109,  110,
       57,   56,  111,  112,  113,  114,  115,  116,   57,  117,
       57,  118,  119,  673,   29,   59,   59,   59,   60,   61,
       59,   59,   59,   59,   62,   59,   63,   59,   64,   65,
       66,   67,   59,   59,   59,   59,   59,   68,   69,   70,
       71,   59,   72,   73,   74,   75,   76,   77,   59,   59,
       78,   59,   79,   59,   59,   59,   59,   59,   59,   46,
       46,   46,   46,   59,   46,   59,   46,   59,   59,   59,
       59,  120,  121,  122,  123,  672,   59,   80,   80,   80,

       80,   80,   80,   80,   80,   80,   80,   46,  102,   59,
       46,   59,   46,  124,   57,  161,   46,  125,   57,  126,
      127,  128,  129,   95,   96,   97,   98,  163,   99,  164,
      100,  162,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,  130,   57,   56,  132,  134,  149,  155,  169,
      667,  101,   56,  217,   47,  150,   46,  135,   46,   46,
      103,   46,  156,   46,   46,   46,   46,   46,  170,  157,
      158,   46,  136,   46,   46,   46,   46,   46,  171,   46,
       46,   46,   46,   46,   46,   46,   46,   46,  172,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,   46,

      176,   46,  177,  178,   46,  179,   46,  180,  181,  182,
      183,  184,   46,   46,   46,  185,   46,  186,  187,  188,
      189,  190,   46,  191,  192,  193,  194,  195,  196,  197,
      198,  199,   46,   46,   46,   46,   46,   46,  218,   57,
      666,  102,  661,  200,  381,  201,  219,   57,  202,   46,
      203,  220,   57,  221,   57,  660,  204,  205,  206,  659,
      207,  222,   57,  223,   57,  382,  208,  224,   57,  225,
       57,  226,   57,  227,   57,  658,  209,  210,  211,  212,
      213,  214,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  657,  103,  228,   57,  229,   57,  230,   57,

      231,   57,  232,   57,  233,   57,  234,   57,  235,   57,
      236,   57,  237,   57,  238,   57,   56,  239,  240,   57,
      241,   57,  242,   57,  243,   57,   56,  244,  245,   57,
      246,   57,  247,   57,  248,   57,   56,  249,  250,   57,
      251,   57,  252,   57,   56,  253,  254,   57,  255,   57,
      273,   46,   46,   46,   46,   46,   46,   46,   46,  305,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,  316,   46,   46,   46,   46,  274,   46,
       46,   46,   46,   46,   46,   46,   46,   46,  328,   46,
       46,   46,   46,  333,   57,  299,  300,  301,   47,  302,

       47,  303,  304,   47,  306,  307,  308,  309,  310,  311,
       47,   47,  312,   47,  313,  314,  315,   47,  317,  318,
      319,  320,   46,  321,  322,  323,  324,  325,   47,   47,
      326,  327,   47,  329,  330,  331,   47,  334,   57,  335,
       57,  336,   57,  337,   57,  338,   57,   56,  340,   56,
      341,  342,   57,  343,   57,   56,  344,  345,   57,  346,
       57,  347,   57,  348,   57,   46,  339,   56,  349,  351,
       57,   56,  352,  353,   57,  354,   57,  355,   57,  356,
       57,  357,   57,   56,  358,   56,  359,  360,   57,   56,
      361,   46,   56,  363,  364,   57,  365,   57,  373,   57,

      385,   57,  397,   57,   46,   46,   46,   46,   46,  350,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,  426,   46,   46,  362,   46,  430,   57,  431,
       57,   56,  432,  433,   57,   46,  435,   57,  402,   47,
      403,   47,  404,   46,  405,   47,   47,  407,  408,  409,
       47,  410,  411,  412,  413,  414,  416,  417,  418,  419,
      420,  421,  422,  423,  424,  425,   47,  428,   47,   46,
       47,  436,   57,  437,   57,   56,  438,   56,  439,  434,
      440,   57,  441,   57,  442,   57,   46,  443,  444,   57,

      445,   57,  446,   57,   56,  447,  448,   57,   56,  449,
      450,   57,  451,   57,  452,   57,  453,   57,  456,   57,
      462,   57,   46,  454,  471,   57,  482,   57,   56,  483,
       46,  486,   46,   46,   46,   46,   46,   46,   46,   46,
      455,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,  507,   57,   46,   56,  509,  510,
       57,   56,  511,  512,   57,   46,   47,   56,  514,  515,
       57,  516,   57,   46,   47,   47,  487,   47,   47,  489,
       47,  490,  491,  492,   46,   47,  494,   47,  495,  496,
      497,  498,  499,  500,  501,   47,  504,  506,  517,   57,

      508,  518,   57,   56,  519,  520,   57,  521,   57,  513,
      524,   57,  526,   57,  528,   57,   46,  522,  533,   57,
       56,  542,  543,   57,   46,   46,   46,   46,  523,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   56,
      561,   46,  563,   57,  564,   57,  565,   57,   56,  566,
       46,  568,   57,  569,   57,  570,   57,   46,   46,  589,
      547,  574,   57,  576,   57,  581,   57,   46,  549,  550,
      551,  552,   46,  554,   47,   47,  555,   47,  556,   47,
       47,   47,  560,  585,   57,  562,   56,  586,   46,  593,
       46,   46,   46,   46,  567,   46,   46,  601,   57,  602,

       57,  571,  572,   47,   46,   46,  604,   57,   46,   46,
       46,   47,  608,   57,  609,   57,  591,  612,   57,   56,
      614,  615,   57,  620,   46,   46,   46,  626,   57,   46,
       46,   46,  592,   47,   47,  595,   47,  599,   46,  600,
       47,  632,   57,  635,   57,  636,   57,   46,  603,   47,
       56,  637,  605,  606,  619,   46,  646,   57,   46,   46,
       46,  651,   57,  653,   57,   56,  654,   46,   47,   47,
      625,  655,   57,   47,  628,  629,   46,   46,   46,   46,
      664,   57,  630,  665,   57,   46,   46,  670,   57,  671,
       57,  640,   46,   46,  675,   57,   46,  656,  652,  645,

      650,  644,  647,  648,  649,  643,  642,  641,  639,  638,
      634,   47,  633,  631,  624,  623,  622,  621,  618,  617,
       47,   47,  662,  663,  616,  613,  611,  610,  607,  668,
      669,  598,  597,  596,  594,  590,  674,   47,  588,  587,
       47,    6,    6,    6,    6,    6,   30,   30,   30,   30,
       30,   34,   34,   34,   34,   34,   38,  584,   38,   38,
       38,   38,   38,  627,  627,  583,  627,  627,  582,  580,
      579,  578,  577,  575,  573,  559,  558,  557,  553,  548,
      546,  545,  544,  541,  540,  539,  538,  537,  536,  535,
      534,  532,  531,  530,  529,  527,  525,  505,  503,  502,

      493,  488,  485,  484,  481,  480,  479,  478,  477,  476,
      475,  474,  473,  472,  470,  469,  468,  467,  466,  465,
      464,  463,  461,  460,  459,  458,  457,  429,  427,  415,
      406,  401,  400,  399,  398,  396,  395,  394,  393,  392,
      391,  390,  389,  388,  387,  386,  384,  383,  380,  379,
      378,  377,  376,  375,  374,  372,  371,  370,  369,  368,
      367,  366,  332,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  280,
      279,  278,  277,  276,  275,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,

      257,  256,  131,  216,  175,  173,  166,  165,  160,  159,
      154,  153,  152,  151,  148,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  133,  131,  104,   81,   58,   38,
       54,   32,   52,   48,   45,   44,   43,   42,   41,   37,
       33,   32,  677,   31,   31,    5,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,

      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677
    } ;

static const flex_int16_t yy_chk[1315] =
    {   0,
        0,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   11,    1,    1,    1,    1,
        1,   34,    1,    1,    1,   36,   53,  683,    0,    0,
      129,   11,  115,  115,  129,    0,   14,   34,  240,    0,
        0,   36,   53,    0,   27,    0,  240,   29,   29,   29,
       46,   59,   40,   47,   47,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,   72,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,   14,    2,    2,    2,    2,    2,   27,    2,
        2,    2,   40,   40,   46,   59,   83,   83,  675,   61,

       62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
       72,   84,   84,   85,   85,   86,   86,   87,   87,   88,
       88,   89,   89,   90,   90,   91,   91,   92,   92,   93,
       93,   94,   94,  671,    2,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   51,   51,   73,
       74,   75,   76,   51,   77,   51,   78,   51,   51,   51,
       51,   95,   95,   96,   96,  670,   51,   51,   51,   51,

       51,   51,   51,   51,   51,   51,   51,   79,   80,   51,
       82,   51,   57,   97,   97,  125,   80,   98,   98,   99,
       99,  100,  100,   73,   74,   75,   76,  126,   77,  126,
       78,  125,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,  101,  101,  103,  103,  105,  117,  122,  130,
      665,   79,  176,  176,   82,  117,  134,  105,  135,  136,
       80,  137,  122,  138,  139,  140,  141,  142,  130,  122,
      122,  143,  105,  144,  145,  146,  147,  148,  130,  149,
      150,  151,  152,  153,  154,  155,  156,  157,  130,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  158,

      134,  159,  135,  136,  160,  137,  161,  138,  139,  140,
      141,  142,  162,  163,  164,  143,  165,  144,  145,  146,
      147,  148,  166,  149,  150,  151,  152,  153,  154,  155,
      156,  157,  167,  168,  169,  170,  171,  172,  177,  177,
      664,  174,  656,  158,  347,  159,  178,  178,  160,  174,
      161,  179,  179,  180,  180,  655,  162,  163,  164,  654,
      165,  181,  181,  182,  182,  347,  166,  183,  183,  184,
      184,  185,  185,  186,  186,  653,  167,  168,  169,  170,
      171,  172,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  651,  174,  187,  187,  188,  188,  189,  189,

      190,  190,  191,  191,  192,  192,  193,  193,  194,  194,
      195,  195,  196,  196,  197,  197,  198,  198,  199,  199,
      200,  200,  201,  201,  202,  202,  203,  203,  204,  204,
      205,  205,  206,  206,  207,  207,  208,  208,  209,  209,
      210,  210,  211,  211,  212,  212,  213,  213,  214,  214,
      233,  257,  258,  259,  260,  261,  262,  263,  264,  265,
      266,  267,  268,  269,  270,  271,  272,  273,  274,  275,
      276,  277,  278,  279,  280,  281,  282,  283,  233,  284,
      285,  286,  287,  288,  289,  290,  291,  292,  293,  294,
      295,  296,  297,  299,  299,  257,  258,  259,  260,  261,

      262,  263,  264,  265,  266,  267,  268,  269,  270,  271,
      272,  273,  274,  275,  276,  277,  278,  279,  280,  281,
      282,  283,  305,  284,  285,  286,  287,  288,  289,  290,
      291,  292,  293,  294,  295,  296,  297,  300,  300,  301,
      301,  302,  302,  303,  303,  304,  304,  306,  306,  307,
      307,  308,  308,  309,  309,  310,  310,  311,  311,  312,
      312,  313,  313,  314,  314,  316,  305,  315,  315,  317,
      317,  318,  318,  319,  319,  320,  320,  321,  321,  322,
      322,  323,  323,  324,  324,  325,  325,  326,  326,  327,
      327,  328,  329,  329,  330,  330,  331,  331,  339,  339,

      350,  350,  362,  362,  367,  368,  369,  370,  371,  316,
      372,  374,  375,  376,  377,  378,  379,  380,  381,  382,
      383,  384,  386,  387,  388,  389,  390,  391,  392,  393,
      394,  395,  396,  398,  399,  328,  400,  402,  402,  403,
      403,  404,  404,  405,  405,  406,  407,  407,  367,  368,
      369,  370,  371,  415,  372,  374,  375,  376,  377,  378,
      379,  380,  381,  382,  383,  384,  386,  387,  388,  389,
      390,  391,  392,  393,  394,  395,  396,  398,  399,  426,
      400,  408,  408,  409,  409,  410,  410,  411,  411,  406,
      412,  412,  413,  413,  414,  414,  427,  415,  416,  416,

      417,  417,  418,  418,  419,  419,  420,  420,  421,  421,
      422,  422,  423,  423,  424,  424,  425,  425,  428,  428,
      434,  434,  458,  426,  443,  443,  454,  454,  455,  455,
      459,  460,  461,  463,  464,  465,  466,  467,  468,  469,
      427,  470,  472,  473,  474,  475,  476,  477,  478,  479,
      480,  481,  484,  486,  487,  487,  488,  489,  489,  490,
      490,  491,  491,  492,  492,  493,  458,  494,  494,  495,
      495,  496,  496,  502,  459,  460,  461,  463,  464,  465,
      466,  467,  468,  469,  503,  470,  472,  473,  474,  475,
      476,  477,  478,  479,  480,  481,  484,  486,  497,  497,

      488,  498,  498,  499,  499,  500,  500,  501,  501,  493,
      504,  504,  506,  506,  508,  508,  527,  502,  513,  513,
      522,  522,  523,  523,  529,  530,  531,  532,  503,  534,
      535,  536,  537,  538,  539,  540,  541,  544,  546,  547,
      547,  548,  549,  549,  550,  550,  551,  551,  552,  552,
      553,  554,  554,  555,  555,  556,  556,  557,  558,  575,
      527,  560,  560,  562,  562,  567,  567,  577,  529,  530,
      531,  532,  578,  534,  535,  536,  537,  538,  539,  540,
      541,  544,  546,  571,  571,  548,  572,  572,  579,  580,
      582,  583,  584,  588,  553,  589,  590,  591,  591,  592,

      592,  557,  558,  575,  593,  594,  595,  595,  596,  597,
      610,  577,  599,  599,  600,  600,  578,  603,  603,  605,
      605,  606,  606,  611,  613,  617,  618,  619,  619,  611,
      621,  622,  579,  580,  582,  583,  584,  588,  623,  589,
      590,  625,  625,  628,  628,  629,  629,  633,  593,  594,
      630,  630,  596,  597,  610,  639,  640,  640,  641,  642,
      643,  645,  645,  647,  647,  648,  648,  652,  613,  617,
      618,  649,  649,  611,  621,  622,  657,  658,  659,  660,
      662,  662,  623,  663,  663,  666,  667,  668,  668,  669,
      669,  633,  672,  673,  674,  674,  676,  650,  646,  639,

      644,  638,  641,  642,  643,  637,  636,  635,  632,  631,
      627,  652,  626,  624,  616,  615,  614,  612,  609,  608,
      657,  658,  659,  660,  607,  604,  602,  601,  598,  666,
      667,  587,  586,  585,  581,  576,  672,  673,  574,  573,
      676,  678,  678,  678,  678,  678,  679,  679,  679,  679,
      679,  680,  680,  680,  680,  680,  681,  570,  681,  681,
      681,  682,  682,  684,  684,  569,  684,  684,  568,  566,
      565,  564,  563,  561,  559,  545,  543,  542,  533,  528,
      526,  525,  524,  521,  520,  519,  518,  517,  516,  515,
      514,  512,  511,  510,  509,  507,  505,  485,  483,  482,

      471,  462,  457,  456,  453,  452,  451,  450,  449,  448,
      447,  446,  445,  444,  442,  441,  440,  439,  438,  437,
      436,  435,  433,  432,  431,  430,  429,  401,  397,  385,
      373,  366,  365,  364,  363,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  349,  348,  346,  345,
      344,  343,  342,  341,  340,  338,  337,  336,  335,  334,
      333,  332,  298,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  239,
      238,  237,  236,  235,  234,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,

      217,  216,  215,  175,  133,  131,  128,  127,  124,  123,
      121,  120,  119,  118,  116,  114,  113,  112,  111,  110,
      109,  108,  107,  106,  104,  102,   81,   52,   49,   39,
       38,   32,   31,   28,   24,   23,   22,   20,   18,   13,
       10,    7,    5,    4,    3,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,

      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[82] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 
    0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "blexer.l"
#line 2 "blexer.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "bparser.tab.h"

/* Indentation tracking */
#define MAX_INDENT_DEPTH 100
int indent_stack[MAX_INDENT_DEPTH];
int indent_top = 0;
int pending_dedents = 0;
int pending_indent = 0;
int paren_depth = 0;

void push_indent(int level) {
    if (indent_top < MAX_INDENT_DEPTH - 1) {
        indent_stack[++indent_top] = level;
    }
}

int pop_indent() {
    if (indent_top > 0) {
        return indent_stack[indent_top--];
    }
    return 0;
}

int get_current_indent() {
    return indent_top > 0 ? indent_stack[indent_top] : 0;
}

void init_indent() {
    indent_top = 0;
    indent_stack[0] = 0;
    pending_dedents = 0;
    pending_indent = 0;
    paren_depth = 0;
}

/* Rename flex's generated scanner so we can wrap it */
#define YY_DECL int internal_yylex(void)

#line 1028 "lex.yy.c"

#line 1030 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 48 "blexer.l"


#line 1251 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 678 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1246 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 50 "blexer.l"
{
    /* Skip newlines inside parentheses/brackets */
    if (paren_depth > 0) {
        /* ignore newlines inside parens */
    } else {
        /* Look ahead: skip blank lines, count indentation of next real line */
        int c;
        int indent;

        while (1) {
            indent = 0;
            while ((c = input()) == ' ') {
                indent++;
            }
            if (c == '\t') {
                /* treat tab as 4 spaces */
                indent += 4;
                continue;
            }
            if (c == '\r') continue;
            if (c == '\n') continue;  /* blank line, try next */
            break;  /* found real content or EOF */
        }

        /* Put back the non-space character we just read */
        if (c != EOF && c != 0) {
            unput(c);
        }

        /* Compare indentation with current level */
        int current = get_current_indent();

        if (indent > current) {
            push_indent(indent);
            pending_indent = 1;
        } else if (indent < current) {
            while (indent_top > 0 && get_current_indent() > indent) {
                pop_indent();
                pending_dedents++;
            }
        }
        /* indent == current: no INDENT/DEDENT needed */

        return NEWLINE;
    }
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "blexer.l"
{ /* Skip carriage return */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 99 "blexer.l"
{ /* Skip whitespace within lines */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 101 "blexer.l"
{ paren_depth++; return LPAREN; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 102 "blexer.l"
{ paren_depth--; return RPAREN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "blexer.l"
{ paren_depth++; return LBRACKET; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 104 "blexer.l"
{ paren_depth--; return RBRACKET; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "blexer.l"
{ return COMMA; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 106 "blexer.l"
{ return COLON; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 107 "blexer.l"
{ return SEMICOLON; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 109 "blexer.l"
{ return PROGRAM_START; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 110 "blexer.l"
{ return PROGRAM_END; }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 112 "blexer.l"
{ yylval.strval = strdup(yytext); return INCLUDE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 114 "blexer.l"
{ return NUMBER_TYPE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 115 "blexer.l"
{ return DECIMAL_TYPE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 116 "blexer.l"
{ return BOOL_TYPE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 117 "blexer.l"
{ return CHAR_TYPE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 118 "blexer.l"
{ return STRING_TYPE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 120 "blexer.l"
{ return IF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 121 "blexer.l"
{ return ELSE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 122 "blexer.l"
{ return WHILE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 123 "blexer.l"
{ return FOR_RANGE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 124 "blexer.l"
{ return FROM; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 125 "blexer.l"
{ return FUNCTION; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 126 "blexer.l"
{ return BREAK; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 127 "blexer.l"
{ return CONTINUE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 128 "blexer.l"
{ return RETURN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 129 "blexer.l"
{ return PRINT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 130 "blexer.l"
{ return INPUT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 132 "blexer.l"
{ return ARRAY; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 134 "blexer.l"
{ return LENGTH; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 135 "blexer.l"
{ return POW; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 136 "blexer.l"
{ return SQRT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 137 "blexer.l"
{ return FLOOR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 138 "blexer.l"
{ return CEIL; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 139 "blexer.l"
{ return ABS; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 141 "blexer.l"
{ return PLUS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 142 "blexer.l"
{ return PLUS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 143 "blexer.l"
{ return MINUS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 144 "blexer.l"
{ return MINUS; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 145 "blexer.l"
{ return MULT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 146 "blexer.l"
{ return MULT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 147 "blexer.l"
{ return DIV; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 148 "blexer.l"
{ return DIV; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 149 "blexer.l"
{ return MOD; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 150 "blexer.l"
{ return MOD; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 151 "blexer.l"
{ return AND; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 152 "blexer.l"
{ return AND; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 153 "blexer.l"
{ return OR; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 154 "blexer.l"
{ return OR; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 155 "blexer.l"
{ return NOT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 156 "blexer.l"
{ return NOT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 157 "blexer.l"
{ return INC; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 158 "blexer.l"
{ return INC; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 159 "blexer.l"
{ return DEC; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 160 "blexer.l"
{ return DEC; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 161 "blexer.l"
{ return EQUAL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 162 "blexer.l"
{ return NOT_EQUAL; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 163 "blexer.l"
{ return GREATER_EQUAL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 164 "blexer.l"
{ return LESS_EQUAL; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 165 "blexer.l"
{ return GREATER; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 166 "blexer.l"
{ return LESS; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 167 "blexer.l"
{ return ASSIGN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 168 "blexer.l"
{ return EQUAL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 169 "blexer.l"
{ return NOT_EQUAL; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 170 "blexer.l"
{ return GREATER_EQUAL; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 171 "blexer.l"
{ return LESS_EQUAL; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 172 "blexer.l"
{ return GREATER; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 173 "blexer.l"
{ return LESS; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 175 "blexer.l"
{ return BOOL_TRUE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 176 "blexer.l"
{ return BOOL_FALSE; }
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 178 "blexer.l"
{ yylval.strval = strdup(yytext); return STRING_LITERAL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 179 "blexer.l"
{ yylval.strval = strdup(yytext); return CHAR_LITERAL; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 181 "blexer.l"
{
    /* Convert Bangla digits to English and parse as float */
    char *english = strdup(yytext);
    int len = strlen(yytext);
    int pos = 0;
    for(int i = 0; i < len; ) {
        if(i + 2 < len && (unsigned char)english[i] == 0xE0 &&
           (unsigned char)english[i+1] == 0xA7 &&
           (unsigned char)english[i+2] >= 0xA6 &&
           (unsigned char)english[i+2] <= 0xAF) {
            int digit = (unsigned char)english[i+2] - 0xA6;
            english[pos++] = '0' + digit;
            i += 3;
        } else {
            english[pos++] = english[i++];
        }
    }
    english[pos] = '\0';
    yylval.floatval = atof(english);
    free(english);
    return FLOAT_LITERAL;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 204 "blexer.l"
{
    /* Convert Bangla digits to English and parse as int */
    char *english = strdup(yytext);
    int len = strlen(yytext);
    int pos = 0;
    for(int i = 0; i < len; ) {
        if(i + 2 < len && (unsigned char)english[i] == 0xE0 &&
           (unsigned char)english[i+1] == 0xA7 &&
           (unsigned char)english[i+2] >= 0xA6 &&
           (unsigned char)english[i+2] <= 0xAF) {
            int digit = (unsigned char)english[i+2] - 0xA6;
            english[pos++] = '0' + digit;
            i += 3;
        } else {
            english[pos++] = english[i++];
        }
    }
    english[pos] = '\0';
    yylval.intval = atoi(english);
    free(english);
    return INT_LITERAL;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 227 "blexer.l"
{ BEGIN(COMMENT); }
	YY_BREAK

case 77:
YY_RULE_SETUP
#line 230 "blexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 231 "blexer.l"
{ }
	YY_BREAK

case 79:
YY_RULE_SETUP
#line 234 "blexer.l"
{ yylval.strval = strdup(yytext); return IDENTIFIER; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 236 "blexer.l"
{ fprintf(stderr, "Unknown character: %s at line %d\n", yytext, yylineno); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
#line 238 "blexer.l"
{
    /* Emit remaining dedents at end of file */
    if (pending_dedents > 0) {
        pending_dedents--;
        return DEDENT;
    }
    if (indent_top > 0) {
        pop_indent();
        return DEDENT;
    }
    yyterminate();
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 251 "blexer.l"
ECHO;
	YY_BREAK
#line 1832 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 678 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 678 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 677);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 251 "blexer.l"


/* Wrapper: emits pending INDENT/DEDENT tokens before calling the real scanner */
int yylex(void) {
    /* First drain any pending INDENT */
    if (pending_indent) {
        pending_indent = 0;
        return INDENT;
    }
    /* Then drain any pending DEDENTs */
    if (pending_dedents > 0) {
        pending_dedents--;
        return DEDENT;
    }
    /* Otherwise get the next token from flex */
    return internal_yylex();
}

