
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[646] =
    {   0,
        0,    0,    0,    0,   79,   77,    1,    1,   48,   77,
       42,   77,   77,    2,    3,   38,   34,    6,   36,   40,
       59,   60,   58,    4,    5,   76,   77,   77,   75,   75,
        1,   55,    0,   69,    0,   44,    0,    0,    0,   50,
       52,   57,   54,   56,   76,    0,   46,    0,    0,    0,
        0,   69,   70,    0,    0,    0,    8,   76,    7,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   72,    0,
       76,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   65,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
        0,   72,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   76,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   71,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   76,   76,   76,   45,   76,   39,   76,   76,
       66,   76,   76,   76,   76,   76,   49,   27,   76,   33,
       76,   76,   76,   76,   76,   76,   76,   76,    0,   41,
       76,   76,   76,   17,   35,   76,   76,   76,   76,   76,
       76,   32,    0,    0,    0,    0,    0,    0,    0,   76,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   76,    0,    0,    0,    0,    0,
        0,   76,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   76,
       47,   76,   53,   76,   76,    0,   23,   21,   76,   76,
       28,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,    0,   76,   76,   76,   76,   76,   76,    0,   76,
       67,   61,    0,    0,    0,    0,    0,   76,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       76,    0,    0,    0,    0,    0,   76,   76,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   15,   62,   76,
       76,    0,   13,   26,   18,   76,   76,   76,   31,   76,
       16,   76,   76,   76,    0,   76,   76,   76,   76,   29,
        0,    0,   76,    0,   76,    0,   76,    0,    0,    0,
        0,    0,    0,    0,   76,    0,    0,    0,    0,   76,
       76,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   76,    0,   76,   76,   76,   76,   51,
       37,   76,    0,   43,   76,   68,   19,    0,    0,   12,
        0,   76,   76,   76,    0,    0,   76,    0,    0,   63,
        0,   76,   76,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   76,
       76,    0,   30,   14,   73,    0,    0,    0,   76,   76,
       64,    0,    0,   76,   76,   76,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   76,   76,    0,
        0,    0,    0,   20,   76,    0,    0,   76,   76,   76,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   22,
       11,    0,    0,    0,    0,   24,   25,   76,   76,    0,
        0,    0,    0,    0,    0,    0,   76,   76,   74,    0,
        0,    0,    0,   76,   76,    0,    0,    0,    0,   76,
       10,    0,    0,    9,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   17,
       18,   19,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       20,   21,   22,    1,   23,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   24,    1,    1,    1,   25,   26,   27,
       28,   25,   29,   25,   30,   25,   25,   25,   31,   25,
       32,   25,   33,   25,   25,   25,   34,   25,   35,   36,
       37,   38,   25,   39,   40,   41,   25,   25,   42,   25,
       43,   25,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   25,   58,   25,   25,
       25,   59,   60,   61,   62,   25,   25,   63,   25,   64,
       65,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   66,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[67] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    2,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    4,    4,    4,    5,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1
    } ;

static const flex_int16_t yy_base[655] =
    {   0,
        0,   65, 1116, 1115, 1180, 1183,   23,   25, 1161,   10,
     1183, 1171,   14, 1183, 1183, 1183, 1165, 1183, 1162, 1183,
     1157, 1156, 1155, 1183, 1183,   20, 1148,    0, 1183, 1124,
       27, 1183,   16, 1183,   28, 1183, 1162, 1161,   43, 1183,
     1183, 1183, 1183, 1183,   27,    5, 1183, 1123,  107,  126,
     1112,   33, 1183,    0,    0,  155, 1183,   32, 1183,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,  161,
      162,  163,  164,  165,  166,  167,  168,  169,  178, 1100,
      171,   47,   49,   62,   64,   66,   68,   70,   72,   74,
       76,   78,   80,   82,  148,  150,  152,  165,  167,  169,

     1099,  171, 1117,  190, 1110, 1107, 1135, 1134, 1095, 1127,
     1093, 1126, 1096, 1124, 1089,  182, 1095, 1119, 1085, 1117,
      183,  198, 1084,  177,  175, 1116, 1111,    6,  214, 1097,
      233, 1095,  198,  200,  226,  227,  229,  230,  231,  232,
      233,  234,  235,  237,  238,  239,  240,  242,  244,  245,
      247,  248,  249,  250,  251,  252,  253,  254,  255,  267,
      268,  271,  279,  284,  286,  289,  299,  300,  301,  302,
        0,  312, 1077,  281,  283,  291,  293,  295,  299,  301,
      306,  309,  311,  313,  315,  322,  324,  326,  328,  332,
      334,  336,  338,  340,  342,  344,  346,  341,  348,  350,

      352,  354,  356,  358,  361,  363,  365,  367,  369,  371,
      373, 1076, 1093, 1108, 1086, 1083, 1110, 1072, 1091, 1077,
     1075, 1090, 1076, 1095, 1074, 1092, 1070, 1063,  388, 1070,
     1067, 1066, 1064, 1089,  301, 1064, 1061,  376, 1081, 1085,
     1070, 1080, 1049, 1076, 1080, 1054, 1050, 1073, 1076, 1043,
     1048, 1073,  402,  403,  404,  405,  406,  407,  408,  409,
      410,  411,  412,  413,  414,  415,  416,  417,  418,  419,
      420,  421,  422,  423,  424,  425,  426,  428, 1043,  429,
      430,  431,  432,  433,  434,  435,  436,  437,  438,  439,
      440,  441, 1037,  418,  461,  463,  465,  467,  469,  470,

      471,  473,  475,  477,  479,  481,  483,  485,  487,  490,
      492,  494,  496,  498,  524,  501,  503,  505,  507,  509,
      511,  537,  514,  516,  518, 1055, 1041, 1036, 1035, 1064,
     1052, 1031,  520, 1064, 1064, 1028, 1028, 1056, 1032,  535,
     1024, 1057, 1050, 1054, 1022, 1021, 1018,  524, 1023, 1036,
     1048, 1047, 1033, 1051,  526, 1044, 1019, 1025, 1028,  546,
      552,  553,  554,  555,  556, 1011,  557,  558,  559,  560,
      561,  562,  563,  564,  565,  566,  569,  570,  571,  572,
      573, 1016,  574,  575,  576,  577,  578,  579, 1019,  581,
      582,  583, 1003,  560,  562,  566,  568,  588,  586,  603,

      605,  608,  610,  612,  614,  616,  618,  620,  622,  624,
      623,  626,  628,  630,  632,  634,  660,  661,  638, 1021,
     1010, 1017, 1035, 1022,  640, 1028, 1028, 1031, 1028,  996,
     1016, 1000, 1001,  999,  990, 1022, 1010,  643, 1021,  997,
      993,  988,  982,  645,  647,  990,  992,  673,  674,  675,
      676,  989,  677,  678,  679,  680,  681,  682,  683,  684,
      685,  686,  687,  688,  979,  689,  690,  691,  692,  693,
      991, 1009,  694,  974,  695,  672,  698,  675,  677,  681,
      683,  685,  687,  689,  715,  715,  718,  720,  722,  748,
      749,  726,  991,  728, 1008,  730,  980, 1005, 1005, 1007,

      999,  995,  967,  732,  970,  997,  964,  983,  735,  737,
      962,  993,  978,  763,  959,  764,  765,  766,  767,  768,
      769,  770,  973,  771,  772,  773,  774,  989,  963,  775,
      953,  776,  777,  778,  755,  757,  783,  760,  762,  788,
      765,  793,  794,  971,  771,  773,  775,  952,  972,  777,
      951,  948,  919,  779,  798,  918,  909,  916,  922,  805,
      824,  923,  825,  827,  828,  912,  937,  942,  829,  830,
      832,  809,  814,  835,  840,  841,  898,  818,  820,  920,
      912,  822,  825,  827,  913,  924,  894,  853,  860,  891,
      923,  916,  893,  855,  856,  833,    0,  859,  861,  862,

      884,  839,  885,  927,  841,  852,  855,  897,  910,  869,
     1183,  909,  905,  909,  909,  874,  881,  882,  885,  872,
      862,  864,  570,  435,  320,  291,  890,  891, 1183,  868,
      870,  275,  262,  897,  900,  882,  884,  181,  188,  901,
      910,  889,   37,  911, 1183,  977,  983,  989,  995,  998,
     1001, 1004,   28, 1010
    } ;

static const flex_int16_t yy_def[655] =
    {   0,
      646,  646,  647,  647,  645,  645,  645,  645,  645,  648,
      645,  645,  649,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  648,  645,  648,  645,  645,  649,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  650,
      645,  648,  645,  651,  652,  652,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,

      645,  645,  645,  652,  652,  652,   56,   56,  652,   56,
      652,   56,  652,   56,  652,  652,  652,   56,  652,   56,
      652,   56,  652,  652,  652,   56,  652,   56,  652,  645,
       56,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      653,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,

      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,   56,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,   56,  652,  652,  652,  645,  652,   56,
      652,  652,  652,  652,   56,  652,  652,  652,   56,  652,
      652,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  652,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,

      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  652,  652,  652,  652,
      652,  652,  645,   56,   56,  652,  652,  652,  652,  652,
      652,   56,  652,   56,  652,  652,  652,  645,  652,  652,
       56,   56,  652,   56,  645,   56,  652,  652,  645,  645,
      645,  645,  645,  645,  645,  652,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  652,  645,  645,  645,  645,  645,  645,  652,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,

      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      652,  652,   56,   56,  645,  652,  652,   56,   56,  652,
       56,  652,  652,  652,  652,   56,   56,  645,   56,  652,
      652,  652,  652,  645,  645,  652,  645,  645,  645,  645,
      645,  652,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  652,  645,  645,  645,  645,  645,
      652,   56,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,   56,  645,  652,   56,   56,   56,

      652,  652,  652,  645,  652,   56,  652,  652,  645,  645,
      652,  645,  652,  645,  652,  645,  645,  645,  645,  645,
      645,  645,  652,  645,  645,  645,  645,   56,  652,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  652,  652,  645,
      652,  652,  652,  645,  645,  645,  652,  652,  652,  645,
      645,  652,  645,  645,  645,  652,   56,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,   56,
      652,  645,  645,  645,  645,  652,  652,  645,  645,  652,
       56,  652,  645,  645,  645,  645,  654,  645,  645,  645,

      645,  645,  652,  654,  645,  645,  645,  645,  652,  645,
      645,  652,  652,   56,  645,  645,  645,  645,  645,  645,
      645,  645,  645,   56,  652,  645,  645,  645,  645,  645,
      645,  652,  652,  645,  645,  645,  645,  652,  652,  645,
      645,  645,  652,  645,    0,  645,  645,  645,  645,  645,
      645,  645,  645,  645
    } ;

static const flex_int16_t yy_nxt[1250] =
    {   0,
      645,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   34,   20,   21,   22,   23,   24,
       34,   25,   26,   27,   31,   31,   31,   31,   31,   31,
       35,  165,   52,  212,   38,  166,   35,   34,  645,  645,
      645,  645,   45,  645,  645,   48,   49,   50,   35,   45,
       53,   55,   56,   35,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   28,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   39,
       20,   21,   22,   23,   24,   46,   25,   26,   27,   54,
       54,  644,   46,  104,   56,  105,   56,   46,   82,   83,

       84,   85,   86,   87,   88,   89,   90,   91,  106,   56,
       55,  107,   55,  108,  109,   56,   55,  110,  111,  112,
      113,  114,  115,   56,  116,   56,  117,  118,  119,  120,
       28,   58,   58,   58,   59,   60,   58,   58,   58,   61,
       58,   62,   58,   63,   64,   65,   66,   58,   58,   58,
       58,   58,   67,   68,   69,   70,   58,   71,   72,   73,
       74,   75,   76,   58,   58,   77,   58,   78,   58,   58,
       58,   58,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,  101,   45,  121,  122,  123,   56,  124,   56,

       45,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,  125,  126,  127,  128,  129,   56,   55,  131,  161,
       45,  162,   45,  156,  133,  159,   92,   93,   94,   95,
       96,   97,   98,   99,  100,  134,   46,  147,  157,  153,
      167,  160,  641,  102,  640,  148,  154,  155,   45,   45,
      135,   45,   45,   45,   45,   45,   45,   45,  168,   45,
       45,   45,   45,  174,   45,  175,   45,   45,  169,   45,
       45,   45,   45,   45,   45,  198,   45,   45,  170,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,   45,
       45,  176,  177,   45,  178,  179,  180,  181,  182,  183,

      184,   45,  185,  186,  187,  188,   45,  189,   45,  190,
      191,   45,  192,  193,  194,  195,  196,  197,   46,  199,
      200,   45,   45,   45,   45,  635,  101,   55,  214,  215,
       56,  634,  201,  202,   45,  275,  203,  216,   56,  217,
       56,  218,   56,  276,  204,  219,   56,  220,   56,  205,
      629,  206,  221,   56,  207,  222,   56,  223,   56,  224,
       56,  225,   56,   45,  208,  209,  210,  211,  226,   56,
      227,   56,  228,   56,  229,   56,  628,  102,  230,   56,
      231,   56,  232,   56,  233,   56,   55,  234,  235,   56,
      236,   56,  237,   56,  239,   56,   55,  240,  241,   56,

      242,   56,  243,   56,  244,   56,  238,   55,  245,  246,
       56,  247,   56,  248,   56,   55,  249,  250,   56,  251,
       56,  268,  279,   56,   45,   45,   45,   45,   45,   45,
       45,   45,  300,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,  269,
       45,   45,   45,   45,   45,   45,   45,   45,   45,  322,
       45,   45,   45,   45,  327,   56,  627,  294,  295,  296,
       46,  297,   46,  298,  299,   46,  301,  302,  303,  304,
      305,   46,   46,  306,   46,  307,  308,  309,  310,  311,
      312,  313,   45,  314,  316,  317,  318,  319,   46,   46,

      320,  321,   46,  323,  324,  325,   46,  328,   56,  329,
       56,  330,   56,  331,   56,  332,   56,   55,  334,   55,
      335,  336,   56,  337,   56,  338,   56,  339,   56,  340,
       56,  341,   56,   55,  342,  333,  343,   56,   55,  344,
      345,   56,  346,   56,  347,   56,   45,  349,   56,  350,
       56,   55,  351,   55,  352,  353,   56,   55,  354,   45,
       55,  356,  357,   56,  358,   56,  366,   56,   45,  373,
      382,   56,  389,   56,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,  348,
      374,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,  417,  355,   45,   45,   45,  421,   56,  422,   56,
       45,  394,   55,  423,   55,  424,  626,   46,  395,   46,
      396,  397,   46,   46,  399,  400,   46,  401,  402,  403,
      404,  405,  426,   56,  406,  407,  408,  409,  410,  412,
      413,  414,  415,  416,   46,   45,  419,   46,   46,  427,
       56,   55,  428,  425,   55,  429,  430,   56,   55,  431,
      432,   56,  433,   56,  434,   56,  435,   56,   55,  436,
       55,  437,   55,  439,  440,   56,  441,   56,  442,   56,
      443,   56,   45,   45,  446,   56,  452,   56,  438,  465,
       56,  471,   56,   55,  472,   45,   45,  475,   45,   45,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   55,  495,
       45,  497,   56,   55,  498,  444,  445,   55,  499,   55,
      500,  501,   56,  502,   56,  503,   56,   45,   46,   46,
       46,  476,   46,   46,   46,  478,  479,  480,   46,  481,
       46,  482,  483,  484,  486,  487,  488,  489,   46,  492,
      494,  505,   56,  496,   55,  506,  507,   56,  508,   56,
       45,   45,  511,   56,  513,   56,  515,   56,  523,   56,
      504,   55,  528,  529,   56,  533,   45,   45,  537,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,  548,   56,  549,   56,   45,  551,   56,  552,   56,
       45,  553,   56,  509,  510,   45,   45,  557,   56,  558,
       56,  559,   56,  562,   56,  566,   56,   45,   46,  535,
      536,   46,  538,   46,   46,  539,   46,  541,   46,   46,
       46,  545,  546,  547,   55,  567,   45,   45,  550,   45,
       45,   45,   45,   46,   45,   55,  580,   45,  554,  555,
      581,   56,   45,   45,  586,   56,  587,   56,  590,   56,
      572,   55,  591,  592,   56,   45,  597,   45,   45,  603,
       56,   45,   45,   45,   45,  609,   56,  612,   56,  573,
       46,   45,   46,   46,  578,  579,   45,   46,  613,   56,

      582,   55,  614,   45,   45,  583,  584,   45,   55,  624,
      625,   56,   45,   45,  632,   56,  633,   56,  596,   45,
       46,  602,   45,   45,  605,   46,  606,  607,  638,   56,
      639,   56,   45,   45,   46,  643,   56,  623,  620,   46,
      619,  618,  617,  616,  615,  611,   46,  621,  610,  608,
      622,  601,  600,  599,  598,  630,  631,  595,  594,  593,
      589,  588,  636,  585,  577,  637,  642,  576,  575,  574,
      571,  570,  569,  568,  565,   46,   46,    6,    6,    6,
        6,    6,    6,   29,   29,   29,   29,   29,   29,   33,
       33,   33,   33,   33,   33,   37,  564,   37,   37,   37,

       37,   58,   58,   58,   37,   37,   37,   45,  563,   45,
      604,  604,  561,  604,  604,  604,  560,  556,  544,  543,
      542,  540,  534,  532,  531,  530,  527,  526,  525,  524,
      522,  521,  520,  519,  518,  517,  516,  514,  512,  493,
      491,  490,  485,  477,  474,  473,  470,  469,  468,  467,
      466,  464,  463,  462,  461,  460,  459,  458,  457,  456,
      455,  454,  453,  451,  450,  449,  448,  447,  420,  418,
      411,  398,  393,  392,  391,  390,  388,  387,  386,  385,
      384,  383,  381,  380,  379,  378,  377,  376,  375,  372,
      371,  370,  369,  368,  367,  365,  364,  363,  362,  361,

      360,  359,  326,  315,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  278,  277,
      274,  273,  272,  271,  270,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  130,  213,  173,  171,  164,  163,  158,  152,  151,
      150,  149,  146,  145,  144,  143,  142,  141,  140,  139,
      138,  137,  136,  132,  130,  103,   80,   57,   37,   53,
       51,   47,   44,   43,   42,   41,   40,   36,   32,  645,
       30,   30,    5,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,

      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645
    } ;

static const flex_int16_t yy_chk[1250] =
    {   0,
        0,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   10,    1,    1,    1,    1,    1,
       33,    1,    1,    1,    7,    7,    8,    8,   31,   31,
       10,  128,   35,  653,   13,  128,   33,   52,    0,    0,
        0,    0,   26,    0,    0,   28,   28,   28,   35,   45,
       39,   46,   46,   52,   58,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,   13,
        2,    2,    2,    2,    2,   26,    2,    2,    2,   39,
       39,  643,   45,   82,   82,   83,   83,   58,   60,   61,

       62,   63,   64,   65,   66,   67,   68,   69,   84,   84,
       85,   85,   86,   86,   87,   87,   88,   88,   89,   89,
       90,   90,   91,   91,   92,   92,   93,   93,   94,   94,
        2,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   56,   70,   71,   72,   73,   74,   75,   76,
       77,   78,   79,   81,   95,   95,   96,   96,   97,   97,

       79,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   98,   98,   99,   99,  100,  100,  102,  102,  125,
      133,  125,  134,  122,  104,  124,   70,   71,   72,   73,
       74,   75,   76,   77,   78,  104,   81,  116,  122,  121,
      129,  124,  639,   79,  638,  116,  121,  121,  135,  136,
      104,  137,  138,  139,  140,  141,  142,  143,  129,  144,
      145,  146,  147,  133,  148,  134,  149,  150,  129,  151,
      152,  153,  154,  155,  156,  157,  158,  159,  129,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  160,
      161,  135,  136,  162,  137,  138,  139,  140,  141,  142,

      143,  163,  144,  145,  146,  147,  164,  148,  165,  149,
      150,  166,  151,  152,  153,  154,  155,  156,  157,  158,
      159,  167,  168,  169,  170,  633,  172,  174,  174,  175,
      175,  632,  160,  161,  172,  235,  162,  176,  176,  177,
      177,  178,  178,  235,  163,  179,  179,  180,  180,  164,
      626,  165,  181,  181,  166,  182,  182,  183,  183,  184,
      184,  185,  185,  198,  167,  168,  169,  170,  186,  186,
      187,  187,  188,  188,  189,  189,  625,  172,  190,  190,
      191,  191,  192,  192,  193,  193,  194,  194,  195,  195,
      196,  196,  197,  197,  199,  199,  200,  200,  201,  201,

      202,  202,  203,  203,  204,  204,  198,  205,  205,  206,
      206,  207,  207,  208,  208,  209,  209,  210,  210,  211,
      211,  229,  238,  238,  253,  254,  255,  256,  257,  258,
      259,  260,  261,  262,  263,  264,  265,  266,  267,  268,
      269,  270,  271,  272,  273,  274,  275,  276,  277,  229,
      278,  280,  281,  282,  283,  284,  285,  286,  287,  288,
      289,  290,  291,  292,  294,  294,  624,  253,  254,  255,
      256,  257,  258,  259,  260,  261,  262,  263,  264,  265,
      266,  267,  268,  269,  270,  271,  272,  273,  274,  275,
      276,  277,  300,  278,  280,  281,  282,  283,  284,  285,

      286,  287,  288,  289,  290,  291,  292,  295,  295,  296,
      296,  297,  297,  298,  298,  299,  299,  301,  301,  302,
      302,  303,  303,  304,  304,  305,  305,  306,  306,  307,
      307,  308,  308,  309,  309,  300,  310,  310,  311,  311,
      312,  312,  313,  313,  314,  314,  315,  316,  316,  317,
      317,  318,  318,  319,  319,  320,  320,  321,  321,  322,
      323,  323,  324,  324,  325,  325,  333,  333,  360,  340,
      348,  348,  355,  355,  361,  362,  363,  364,  365,  367,
      368,  369,  370,  371,  372,  373,  374,  375,  376,  315,
      340,  377,  378,  379,  380,  381,  383,  384,  385,  386,

      387,  388,  322,  390,  391,  392,  394,  394,  395,  395,
      398,  360,  396,  396,  397,  397,  623,  361,  362,  363,
      364,  365,  367,  368,  369,  370,  371,  372,  373,  374,
      375,  376,  399,  399,  377,  378,  379,  380,  381,  383,
      384,  385,  386,  387,  388,  411,  390,  391,  392,  400,
      400,  401,  401,  398,  402,  402,  403,  403,  404,  404,
      405,  405,  406,  406,  407,  407,  408,  408,  409,  409,
      410,  410,  412,  412,  413,  413,  414,  414,  415,  415,
      416,  416,  417,  418,  419,  419,  425,  425,  411,  438,
      438,  444,  444,  445,  445,  448,  449,  450,  451,  453,

      454,  455,  456,  457,  458,  459,  460,  461,  462,  463,
      464,  466,  467,  468,  469,  470,  473,  475,  476,  476,
      477,  478,  478,  479,  479,  417,  418,  480,  480,  481,
      481,  482,  482,  483,  483,  484,  484,  485,  448,  449,
      450,  451,  453,  454,  455,  456,  457,  458,  459,  460,
      461,  462,  463,  464,  466,  467,  468,  469,  470,  473,
      475,  486,  486,  477,  487,  487,  488,  488,  489,  489,
      490,  491,  492,  492,  494,  494,  496,  496,  504,  504,
      485,  509,  509,  510,  510,  514,  516,  517,  518,  519,
      520,  521,  522,  524,  525,  526,  527,  530,  532,  533,

      534,  535,  535,  536,  536,  537,  538,  538,  539,  539,
      540,  541,  541,  490,  491,  542,  543,  545,  545,  546,
      546,  547,  547,  550,  550,  554,  554,  560,  514,  516,
      517,  518,  519,  520,  521,  522,  524,  525,  526,  527,
      530,  532,  533,  534,  555,  555,  561,  563,  537,  564,
      565,  569,  570,  540,  571,  572,  572,  574,  542,  543,
      573,  573,  575,  576,  578,  578,  579,  579,  582,  582,
      560,  583,  583,  584,  584,  588,  589,  594,  595,  596,
      596,  598,  589,  599,  600,  602,  602,  605,  605,  561,
      563,  610,  564,  565,  569,  570,  616,  571,  606,  606,

      574,  607,  607,  617,  618,  575,  576,  619,  621,  621,
      622,  622,  627,  628,  630,  630,  631,  631,  588,  634,
      594,  595,  635,  640,  598,  589,  599,  600,  636,  636,
      637,  637,  641,  644,  610,  642,  642,  620,  615,  616,
      614,  613,  612,  609,  608,  604,  617,  618,  603,  601,
      619,  593,  592,  591,  590,  627,  628,  587,  586,  585,
      581,  580,  634,  577,  568,  635,  640,  567,  566,  562,
      559,  558,  557,  556,  553,  641,  644,  646,  646,  646,
      646,  646,  646,  647,  647,  647,  647,  647,  647,  648,
      648,  648,  648,  648,  648,  649,  552,  649,  649,  649,

      649,  650,  650,  650,  651,  651,  651,  652,  551,  652,
      654,  654,  549,  654,  654,  654,  548,  544,  531,  529,
      528,  523,  515,  513,  512,  511,  508,  507,  506,  505,
      503,  502,  501,  500,  499,  498,  497,  495,  493,  474,
      472,  471,  465,  452,  447,  446,  443,  442,  441,  440,
      439,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  424,  423,  422,  421,  420,  393,  389,
      382,  366,  359,  358,  357,  356,  354,  353,  352,  351,
      350,  349,  347,  346,  345,  344,  343,  342,  341,  339,
      338,  337,  336,  335,  334,  332,  331,  330,  329,  328,

      327,  326,  293,  279,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  237,  236,
      234,  233,  232,  231,  230,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  173,  132,  130,  127,  126,  123,  120,  119,
      118,  117,  115,  114,  113,  112,  111,  110,  109,  108,
      107,  106,  105,  103,  101,   80,   51,   48,   38,   37,
       30,   27,   23,   22,   21,   19,   17,   12,    9,    5,
        4,    3,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,

      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645,  645,
      645,  645,  645,  645,  645,  645,  645,  645,  645
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[79] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "blexer.l"
#line 2 "blexer.l"
#include <stdio.h>
#line 962 "lex.yy.c"
 
#line 964 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 9 "blexer.l"


#line 1185 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 646 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1183 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 11 "blexer.l"
{ /* skip whitespace */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 13 "blexer.l"
{ printf("TOKEN: LPAREN (%s)\n", yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 14 "blexer.l"
{ printf("TOKEN: RPAREN (%s)\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 15 "blexer.l"
{ printf("TOKEN: LBRACKET (%s)\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 16 "blexer.l"
{ printf("TOKEN: RBRACKET (%s)\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 17 "blexer.l"
{ printf("TOKEN: COMMA (%s)\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 18 "blexer.l"
{ printf("TOKEN: COLON (%s)\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 19 "blexer.l"
{ printf("TOKEN: SEMICOLON (%s)\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 21 "blexer.l"
{ printf("TOKEN: PROGRAM_START (%s)\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 22 "blexer.l"
{ printf("TOKEN: PROGRAM_END (%s)\n", yytext); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 24 "blexer.l"
{ printf("TOKEN: INCLUDE (%s)\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 "blexer.l"
{ printf("TOKEN: NUMBER_TYPE (%s)\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 "blexer.l"
{ printf("TOKEN: DECIMAL_TYPE (%s)\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 28 "blexer.l"
{ printf("TOKEN: BOOL_TYPE (%s)\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 29 "blexer.l"
{ printf("TOKEN: CHAR_TYPE (%s)\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 30 "blexer.l"
{ printf("TOKEN: STRING_TYPE (%s)\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 32 "blexer.l"
{ printf("TOKEN: IF (%s)\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 33 "blexer.l"
{ printf("TOKEN: ELSE (%s)\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 34 "blexer.l"
{ printf("TOKEN: WHILE (%s)\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 35 "blexer.l"
{ printf("TOKEN: FOR_RANGE (%s)\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 36 "blexer.l"
{ printf("TOKEN: FROM (%s)\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 37 "blexer.l"
{ printf("TOKEN: FUNCTION (%s)\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 38 "blexer.l"
{ printf("TOKEN: BREAK (%s)\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 39 "blexer.l"
{ printf("TOKEN: CONTINUE (%s)\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 40 "blexer.l"
{ printf("TOKEN: RETURN (%s)\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 41 "blexer.l"
{ printf("TOKEN: PRINT (%s)\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 42 "blexer.l"
{ printf("TOKEN: INPUT (%s)\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 44 "blexer.l"
{ printf("TOKEN: ARRAY (%s)\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 46 "blexer.l"
{ printf("TOKEN: POW (%s)\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 47 "blexer.l"
{ printf("TOKEN: SQRT (%s)\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 48 "blexer.l"
{ printf("TOKEN: FLOOR (%s)\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 49 "blexer.l"
{ printf("TOKEN: CEIL (%s)\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 50 "blexer.l"
{ printf("TOKEN: ABS (%s)\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 52 "blexer.l"
{ printf("TOKEN: PLUS (%s)\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 53 "blexer.l"
{ printf("TOKEN: PLUS (%s)\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 54 "blexer.l"
{ printf("TOKEN: MINUS (%s)\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 55 "blexer.l"
{ printf("TOKEN: MINUS (%s)\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 56 "blexer.l"
{ printf("TOKEN: MULT (%s)\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 57 "blexer.l"
{ printf("TOKEN: MULT (%s)\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 58 "blexer.l"
{ printf("TOKEN: DIV (%s)\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 59 "blexer.l"
{ printf("TOKEN: DIV (%s)\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 60 "blexer.l"
{ printf("TOKEN: MOD (%s)\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 61 "blexer.l"
{ printf("TOKEN: MOD (%s)\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 62 "blexer.l"
{ printf("TOKEN: AND (%s)\n", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 63 "blexer.l"
{ printf("TOKEN: AND (%s)\n", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 64 "blexer.l"
{ printf("TOKEN: OR (%s)\n", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 65 "blexer.l"
{ printf("TOKEN: OR (%s)\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 66 "blexer.l"
{ printf("TOKEN: NOT (%s)\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 67 "blexer.l"
{ printf("TOKEN: NOT (%s)\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 68 "blexer.l"
{ printf("TOKEN: INC (%s)\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 69 "blexer.l"
{ printf("TOKEN: INC (%s)\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 70 "blexer.l"
{ printf("TOKEN: DEC (%s)\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 71 "blexer.l"
{ printf("TOKEN: DEC (%s)\n", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 72 "blexer.l"
{ printf("TOKEN: EQUAL (%s)\n", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 73 "blexer.l"
{ printf("TOKEN: NOT_EQUAL (%s)\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 74 "blexer.l"
{ printf("TOKEN: GREATER_EQUAL (%s)\n", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 75 "blexer.l"
{ printf("TOKEN: LESS_EQUAL (%s)\n", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 76 "blexer.l"
{ printf("TOKEN: GREATER (%s)\n", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 77 "blexer.l"
{ printf("TOKEN: LESS (%s)\n", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 78 "blexer.l"
{ printf("TOKEN: ASSIGN (%s)\n", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 79 "blexer.l"
{ printf("TOKEN: EQUAL (%s)\n", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 80 "blexer.l"
{ printf("TOKEN: NOT_EQUAL (%s)\n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 81 "blexer.l"
{ printf("TOKEN: GREATER_EQUAL (%s)\n", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 82 "blexer.l"
{ printf("TOKEN: LESS_EQUAL (%s)\n", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 83 "blexer.l"
{ printf("TOKEN: GREATER (%s)\n", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 84 "blexer.l"
{ printf("TOKEN: LESS (%s)\n", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 86 "blexer.l"
{ printf("TOKEN: BOOL_TRUE (%s)\n", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 87 "blexer.l"
{ printf("TOKEN: BOOL_FALSE (%s)\n", yytext); }
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 89 "blexer.l"
{ printf("TOKEN: STRING_LITERAL (%s)\n", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 90 "blexer.l"
{ printf("TOKEN: CHAR_LITERAL (%s)\n", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 92 "blexer.l"
{ printf("TOKEN: FLOAT_LITERAL (%s)\n", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 93 "blexer.l"
{ printf("TOKEN: INT_LITERAL (%s)\n", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 95 "blexer.l"
{ BEGIN(COMMENT); }   
	YY_BREAK

case 74:
YY_RULE_SETUP
#line 98 "blexer.l"
{ BEGIN(INITIAL); }  
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 99 "blexer.l"
{ }
	YY_BREAK

case 76:
YY_RULE_SETUP
#line 102 "blexer.l"
{ printf("TOKEN: IDENTIFIER (%s)\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 104 "blexer.l"
{ printf("TOKEN: UNKNOWN (%s)\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 106 "blexer.l"
ECHO;
	YY_BREAK
#line 1648 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 646 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 646 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 645);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 106 "blexer.l"


int main(int argc, char *argv[])
{
    if(argc < 2) {
        printf("Usage: %s <input_file>\n", argv[0]);
        return 1;
    }

    FILE *fp = fopen(argv[1], "r");
    if(!fp) {
        printf("File open error\n");
        return 1;
    }

    yyin = fp;
    yylex();
    fclose(fp);
    return 0;
}


