
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[662] =
    {   0,
        0,    0,    0,    0,   81,   79,    3,    1,    2,   50,
       79,   44,   79,   79,    4,    5,   40,   36,    8,   38,
       42,   61,   62,   60,    6,    7,   78,   79,   79,   77,
       77,    3,   57,    0,   71,    0,   46,    0,    0,    0,
       52,   54,   59,   56,   58,   78,    0,   48,    0,    0,
        0,    0,   71,   72,    0,    0,    0,   10,   78,    9,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   74,
        0,   78,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,    0,   74,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   73,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   78,   78,   78,   47,   78,   41,   78,
       78,   68,   78,   78,   78,   78,   78,   51,   29,   78,
       35,   78,   78,   78,   67,   78,   78,   78,   78,   78,
       43,   78,   78,   78,   19,   37,   78,   78,   78,   78,
       78,   78,   34,    0,    0,    0,    0,    0,    0,    0,

       78,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       78,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   78,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       78,   49,   78,   55,   78,   78,    0,   25,   23,   78,
       78,   30,   78,   78,   78,   78,   78,    0,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,    0,
       78,   69,   63,    0,    0,    0,    0,    0,   78,    0,

        0,    0,    0,    0,    0,    0,   78,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   78,   78,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   17,   64,
       78,   78,    0,   15,   28,   20,   78,   78,   78,   33,
        0,   78,   18,   78,   78,   78,   78,   78,   78,   78,
       31,    0,    0,   78,    0,   78,    0,   78,    0,    0,
        0,   78,    0,    0,    0,    0,    0,    0,    0,    0,
       78,   78,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   78,    0,   78,   78,   78,    0,
       78,   53,   39,   78,   45,   78,   70,   21,    0,    0,
       14,    0,   78,    0,   78,    0,    0,    0,   78,    0,
        0,    0,   78,   78,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   78,
        0,   78,   78,   78,    0,   32,   78,   75,    0,    0,
        0,   78,   78,   66,    0,    0,   78,   65,    0,   78,
       78,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   78,   78,    0,   16,    0,    0,    0,

       22,   78,    0,    0,   78,   78,   78,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   78,   13,    0,    0,
        0,    0,   78,    0,   78,   78,   78,    0,    0,    0,
        0,    0,    0,    0,    0,   24,    0,    0,    0,    0,
       26,   27,   78,   78,   76,    0,    0,    0,    0,   78,
       78,    0,    0,    0,    0,   78,   12,    0,    0,   11,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   18,
       19,   20,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       21,   22,   23,    1,   24,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   25,    1,    1,    1,   26,   27,   28,
       29,   26,   30,   26,   31,   26,   26,   26,   32,   26,
       33,   26,   34,   26,   26,   26,   35,   26,   36,   37,
       38,   39,   26,   40,   41,   42,   26,   26,   43,   26,
       44,   26,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   26,   59,   26,   26,
       26,   60,   61,   62,   63,   26,   26,   64,   26,   65,
       66,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   67,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    4,    4,    4,    5,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1
    } ;

static const flex_int16_t yy_base[670] =
    {   0,
        0,   66, 1142, 1141, 1207, 1210, 1204, 1210, 1210, 1186,
       10, 1210, 1196,   15, 1210, 1210, 1210, 1190, 1210, 1187,
     1210, 1182, 1181, 1180, 1210, 1210,   21, 1173,    0, 1210,
     1149, 1194, 1210,   16, 1210,   20, 1210, 1186, 1185,   44,
     1210, 1210, 1210, 1210, 1210,   27,    6, 1210, 1147,  108,
        8, 1136,   21, 1210,    0,    0,  146, 1210,   28, 1210,
       42,  152,  153,  154,  155,  156,  157,  158,  159,  160,
      161,  162,  163,  164,  165,  166,  167,  168,  169,  188,
     1124,  181,   48,   50,   52,   54,   56,   58,   62,   64,
       66,   68,   70,   72,   74,   76,   78,   80,   82,  158,

      160, 1123,  162, 1141,  202, 1134, 1131, 1159, 1158, 1119,
     1151, 1117, 1150, 1120, 1148, 1113,  180, 1119, 1143, 1109,
     1141,  195, 1146, 1107,  190,  167, 1139, 1134,    2,  213,
     1120,  232, 1118,  190,  223,  226,  227,  228,  230,  234,
      238,  239,  241,  242,  243,  244,  246,  247,  248,  249,
      250,  251,  252,  253,  254,  267,  268,  272,  274,  275,
      276,  278,  279,  280,  283,  288,  298,  299,  300,  301,
      302,  322,  313, 1100,  168,  194,  279,  282,  284,  300,
      303,  305,  308,  310,  312,  314,  333,  335,  337,  339,
      341,  343,  345,  347,  349,  351,  353,  355,  357,  359,

      361,  363,  365,  367,  369,  371,  373,  375,  377,  379,
      381,  383, 1099, 1116, 1131, 1109, 1106, 1133, 1095, 1114,
     1100, 1098, 1113, 1099, 1118, 1097, 1115, 1093, 1086,  183,
     1093, 1090, 1089, 1087, 1081, 1111,    0, 1086, 1083, 1103,
     1107, 1092, 1102, 1071, 1098, 1102, 1076, 1072, 1095, 1098,
     1065, 1070, 1095,  409,  410,  411,  412,  413,  414,  415,
      416,  417,  418,  419,  420,  421,  422,  423,  424,  425,
      426,  427,  428,  429,  430,  431,  432,  433,  434,  435,
      436,  437,  438,  439,  440,  441,  442,  443,  444,  445,
      446,  447,  448, 1060,  425,  468,  470,  472,  474,  476,

      502,  479,  481,  483,  485,  487,  489,  491,  493,  495,
      521,  498,  500,  502,  504,  506,  508,  510,  512,  514,
      516,  518,  544,  522,  524,  526, 1078, 1064, 1059, 1058,
     1087, 1075, 1054,  528, 1087, 1087, 1051, 1051, 1079, 1055,
      542, 1047, 1080,  531, 1073, 1077, 1045, 1044, 1041, 1046,
     1059, 1071, 1070, 1056, 1074,  533, 1067, 1042, 1048, 1051,
      559,  560,  561,  562,  563,  565, 1034,  566,  567,  568,
      569,  570,  571,  572,  573,  574,  576, 1033,  577,  578,
      579,  580,  581,  582,  583,  584,  585,  586,  588, 1042,
      589,  590,  591, 1026,  568,  570,  572,  574,  600,  611,

      613,  615,  617,  620,  622,  624,  607,  627,  629,  631,
      633,  635,  637,  639,  641,  643,  645,  630,  671,  650,
     1044, 1033, 1040, 1058, 1031,  652, 1051, 1051, 1054, 1051,
     1019, 1025, 1023,  654, 1024, 1022, 1013, 1045, 1019, 1044,
     1020, 1016, 1011, 1005,  656,  658, 1013, 1015,  672,  684,
      685,  686, 1012,  687,  688,  689,  690,  691,  692,  693,
     1011,  694,  695,  696,  697,  698,  699,  700,  701,  702,
      703, 1014, 1032,  704,  997,  705,  682,  708,  685,  687,
      692,  713,  694,  696,  698,  700,  725,  728,  730,  733,
      726,  759,  736, 1014,  738,  998,  740, 1003, 1028,  995,

      742, 1030, 1022, 1018,  991,  993, 1020,  987, 1006,  746,
      748,  985, 1016, 1001,  768,  982,  774,  775,  776,  981,
      777,  778,  779,  780,  781,  782,  783,  784, 1012,  986,
      785,  976,  786,  763,  789,  766,  768,  770,  796,  773,
      775,  779,  801,  805,  994,  782, 1010,  784,  974,  997,
     1005,  788,  967,  943,  950,  790,  806,  949,  940,  810,
      954,  816,  833,  834,  953,  835,  836,  837,  944,  969,
      975,  838,  840,  841,  818,  821,  847,  849,  826,  852,
      854,  929,  831,  833,  938,  944,  836,  943,  838,  840,
      944,  951,  929,  866,  873,  937,  868,  952,  945,  922,

      869,  870,  847,    0,  874,  875,  882,  914,  861,  916,
      959,  863,  869,  874,  929,  911,  889, 1210,  909,  935,
      939,  940,  891,  876,  896,  902,  903,  901,  880,  902,
      882,  890,  895,  594,  590,  908,  440,  331,  286,  279,
      910,  921,  922,  923, 1210,  902,  904,  280,  271,  924,
      930,  911,  913,  179,   76,  931,  933,  916,   52,  942,
     1210, 1009, 1014, 1019, 1024, 1026, 1028,   24, 1033
    } ;

static const flex_int16_t yy_def[670] =
    {   0,
      662,  662,  663,  663,  661,  661,  661,  661,  661,  661,
      664,  661,  661,  665,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  664,  661,  664,  661,  661,  665,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      666,  661,  664,  661,  667,  668,  668,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,

      661,  661,  661,  661,  668,  668,  668,   57,   57,  668,
       57,  668,   57,  668,   57,  668,  668,  668,   57,  668,
       57,  668,   57,  668,  668,  668,   57,  668,   57,  668,
      661,   57,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,

      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,   57,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,   57,  668,  668,  668,  668,
       57,  668,  668,  668,  668,   57,  668,  668,  668,   57,
      668,  668,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,

      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  668,  668,  668,
      668,  668,  668,  661,   57,   57,  668,  668,  668,  668,
      668,  668,   57,  661,  668,   57,  668,  668,  668,  668,
      668,   57,   57,  668,   57,  661,   57,  668,  668,  661,
      661,  661,  661,  661,  661,  661,  668,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  668,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  668,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,

      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  668,  668,   57,  668,  661,  668,  668,   57,   57,
      668,  668,  668,  661,  668,  668,  668,   57,  668,   57,
      668,  668,  668,  668,  661,  661,  668,  661,  661,  661,
      661,  661,  668,  661,  661,  661,  661,  661,  661,  661,
      668,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  668,   57,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  668,  661,  668,   57,  668,

      661,   57,  668,  668,  668,  668,   57,  668,  668,  661,
      661,  668,  661,  668,  661,  668,  661,  661,  661,  668,
      661,  661,  661,  661,  661,  661,  661,  661,   57,  668,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,   57,  661,  668,  668,
       57,  661,  668,  668,  668,  661,  661,  661,  668,  661,
      668,  661,  661,  661,  668,  661,  661,  661,  668,   57,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  668,  668,  661,  668,  661,  661,
      661,  668,  668,  661,  661,  668,  661,   57,  668,  661,

      661,  661,  661,  669,  661,  661,  661,  661,  661,  668,
      669,  661,  661,  661,  661,  668,  661,  661,  668,  668,
       57,  661,  661,  661,  661,  661,  661,  661,  661,  668,
      661,  661,  661,  661,  668,  661,  668,   57,  668,  661,
      661,  661,  661,  661,  661,  661,  661,  668,  668,  661,
      661,  661,  661,  668,  668,  661,  661,  661,  668,  661,
        0,  661,  661,  661,  661,  661,  661,  661,  661
    } ;

static const flex_int16_t yy_nxt[1278] =
    {   0,
      661,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   35,   21,   22,   23,   24,
       25,   35,   26,   27,   28,   53,   35,   46,  166,  661,
      661,   36,  167,  661,  661,  277,   39,   36,  661,  661,
      661,   36,   36,  278,   46,  661,   49,   50,   51,  661,
       46,   46,   54,   56,   57,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   46,   29,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   40,   21,   22,   23,   24,   25,   47,   26,   27,
       28,   55,   55,   47,   47,  105,   57,  106,   57,  107,

       57,   56,  108,   56,  109,  110,   57,  660,   83,   56,
      111,  112,  113,  114,  115,  116,   57,  117,   57,  118,
      119,  120,  121,  122,  123,  124,   57,  125,   57,  126,
      127,  657,   29,   59,   59,   59,   60,   61,   59,   59,
       59,   62,   59,   63,   59,   64,   65,   66,   67,   59,
       59,   59,   59,   59,   68,   69,   70,   71,   59,   72,
       73,   74,   75,   76,   77,   59,   59,   78,   59,   79,
       59,   59,   59,   59,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   82,   82,   82,   82,   82,   82,   82,

       82,   82,   82,  102,   46,  128,  129,  130,   57,   56,
      132,   46,  162,   46,  163,   56,  215,  269,   84,   85,
       86,   87,   88,   89,   90,   91,   92,   93,   94,   95,
       96,   97,   98,   99,  100,  101,  148,  134,  154,  160,
      168,  216,   57,  656,  149,  270,   46,   47,  135,   46,
       46,   46,  155,   46,  103,  161,  175,   46,  169,  156,
      157,   46,   46,  136,   46,   46,   46,   46,  170,   46,
       46,   46,   46,   46,   46,   46,   46,   46,  171,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  176,
       46,   46,  177,  178,  179,   46,  180,   46,   46,   46,

      181,   46,   46,   46,  182,  183,   46,  184,  185,  186,
      187,   46,  188,  189,  190,  191,  192,  193,  194,  195,
      196,   46,   46,   46,   46,   46,  217,   57,  102,  218,
       57,  219,   57,  197,  198,  651,   46,  650,  199,  645,
      200,  201,  202,  644,  203,  204,  205,  220,   57,  206,
      221,   57,  222,   57,  207,  223,   57,  224,   57,  225,
       57,  226,   57,  643,  208,  209,  210,  211,  212,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  103,
      227,   57,  228,   57,  229,   57,  230,   57,  231,   57,
      232,   57,  233,   57,  234,   57,  235,   57,   56,  236,

      237,   57,  238,   57,  239,   57,  240,   57,   56,  241,
      242,   57,  243,   57,  244,   57,  245,   57,   56,  246,
      247,   57,  248,   57,  249,   57,   56,  250,  251,   57,
      252,   57,   46,   46,   46,   46,   46,   46,   46,   46,
      301,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,  311,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,  323,   46,   46,
       46,   46,  328,   57,  642,  295,  296,  297,   47,  298,
       47,  299,  300,   47,  302,  303,  304,  305,  306,   47,
       47,  307,   47,  308,  309,  310,   47,  312,  313,  314,

      315,  316,  317,  318,  319,  320,   47,   47,  321,  322,
       47,  324,  325,  326,   47,  329,   57,  330,   57,  331,
       57,  332,   57,  333,   57,   46,   56,  335,   56,  336,
      337,   57,  338,   57,  339,   57,  340,   57,  341,   57,
      342,   57,   56,  343,   46,  345,   57,   56,  346,  347,
       57,  348,   57,  349,   57,  350,   57,  351,   57,   56,
      352,   56,  353,  354,   57,   56,  355,   46,  334,   56,
      357,  358,   57,  359,   57,  367,   57,  374,  378,   57,
      390,   57,   46,   46,   46,   46,   46,  344,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,  375,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
      356,  418,   46,   46,   46,  422,   57,  423,   57,   56,
      424,  425,   57,   46,  641,  395,   47,  396,   47,  397,
       46,  398,   47,   47,  400,  401,   47,  402,  403,  404,
      405,  640,  406,  408,  409,  410,  411,  412,  413,  414,
      415,  416,  417,   46,   47,  420,   47,   47,  427,   57,
      428,   57,   56,  429,   56,  430,  426,  431,   57,  432,
       57,  433,   57,  434,  435,   57,  436,   57,  437,   57,
       56,  438,  439,   57,   56,  440,  441,   57,  442,   57,
      443,   57,  444,   57,   46,   46,  445,  447,   57,  453,

       57,  461,   57,  472,   57,   56,  473,   46,  476,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,  496,
       57,   46,  498,   57,   56,  499,   46,  446,   47,  500,
       57,   56,  502,  503,   57,  504,   57,  505,   57,   46,
       47,   47,  477,   47,   47,   47,  479,  480,  481,   47,
      483,   47,  484,  485,  486,  487,  488,  489,  490,   47,
      493,  495,  506,   57,  497,   56,  507,  508,   57,  501,
      509,   57,   46,  512,   57,  514,   57,  516,   57,  520,
       57,   46,  510,   56,  529,  530,   57,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       56,  547,   46,  549,   57,  550,   57,   56,  551,   46,
      553,   57,  554,   57,   46,  511,  555,   57,   46,  559,
       57,  561,   57,  573,  534,  565,   57,  569,   57,   46,
      536,  537,  538,  540,   47,   47,  541,   47,  542,   47,
       47,   47,  546,   56,  570,  548,   46,  577,   46,   46,
       46,   46,  552,   46,   46,  585,   57,  556,  586,   57,
       46,  557,   46,  588,   57,   46,   47,   46,  592,   57,
      593,   57,  575,  596,   57,   56,  598,  599,   57,   46,
      604,   46,   46,   46,  610,   57,   46,   46,   46,  576,

       47,   47,  579,   47,  583,   46,  584,   47,  616,   57,
      619,   57,   46,  587,   46,   47,  620,   57,  589,   46,
      590,   56,  621,  630,   57,   46,   46,  635,   57,  637,
       57,   46,  603,   46,   47,   47,  609,   56,  638,   47,
      612,  613,  639,   57,   46,   46,   46,   46,  614,  648,
       57,  649,   57,   46,   46,  624,   46,  629,  654,   57,
      655,   57,  631,  659,   57,   46,  636,  634,  632,  633,
      628,  627,  626,  625,   47,  623,   47,  622,  618,  617,
      615,  608,  607,  606,  605,  602,  601,   47,  646,  647,
      652,  600,  597,  595,  594,  591,  653,  658,  582,   47,

      581,  580,  578,  574,  572,  571,  568,  567,   47,    6,
        6,    6,    6,    6,   30,   30,   30,   30,   30,   34,
       34,   34,   34,   34,   38,  566,   38,   38,   38,   59,
       59,   38,   38,  611,  611,  564,  611,  611,  563,  562,
      560,  558,  545,  544,  543,  539,  535,  533,  532,  531,
      528,  527,  526,  525,  524,  523,  522,  521,  519,  518,
      517,  515,  513,  494,  492,  491,  482,  478,  475,  474,
      471,  470,  469,  468,  467,  466,  465,  464,  463,  462,
      460,  459,  458,  457,  456,  455,  454,  452,  451,  450,
      449,  448,  421,  419,  407,  399,  394,  393,  392,  391,

      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,
      379,  377,  376,  373,  372,  371,  370,  369,  368,  366,
      365,  364,  363,  362,  361,  360,  327,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  276,  275,  274,  273,  272,  271,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  131,  214,  174,  172,  165,
      164,  159,  158,  153,  152,  151,  150,  147,  146,  145,
      144,  143,  142,  141,  140,  139,  138,  137,  133,  131,
      104,   81,   58,   38,   54,   32,   52,   48,   45,   44,

       43,   42,   41,   37,   33,   32,  661,   31,   31,    5,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661
    } ;

static const flex_int16_t yy_chk[1278] =
    {   0,
        0,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   11,    1,    1,    1,    1,
        1,   34,    1,    1,    1,   36,   53,  668,  129,    0,
        0,   11,  129,    0,    0,  237,   14,   34,    0,    0,
        0,   36,   53,  237,   27,    0,   29,   29,   29,    0,
       46,   59,   40,   47,   47,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   61,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,   14,    2,    2,    2,    2,    2,   27,    2,    2,
        2,   40,   40,   46,   59,   83,   83,   84,   84,   85,

       85,   86,   86,   87,   87,   88,   88,  659,   61,   89,
       89,   90,   90,   91,   91,   92,   92,   93,   93,   94,
       94,   95,   95,   96,   96,   97,   97,   98,   98,   99,
       99,  655,    2,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   57,   62,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
       77,   78,   79,   57,   57,   57,   57,   57,   57,   57,

       57,   57,   57,   80,   82,  100,  100,  101,  101,  103,
      103,   80,  126,  134,  126,  175,  175,  230,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   75,   76,   77,   78,   79,  117,  105,  122,  125,
      130,  176,  176,  654,  117,  230,  135,   82,  105,  136,
      137,  138,  122,  139,   80,  125,  134,  140,  130,  122,
      122,  141,  142,  105,  143,  144,  145,  146,  130,  147,
      148,  149,  150,  151,  152,  153,  154,  155,  130,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  135,
      156,  157,  136,  137,  138,  158,  139,  159,  160,  161,

      140,  162,  163,  164,  141,  142,  165,  143,  144,  145,
      146,  166,  147,  148,  149,  150,  151,  152,  153,  154,
      155,  167,  168,  169,  170,  171,  177,  177,  173,  178,
      178,  179,  179,  156,  157,  649,  173,  648,  158,  640,
      159,  160,  161,  639,  162,  163,  164,  180,  180,  165,
      181,  181,  182,  182,  166,  183,  183,  184,  184,  185,
      185,  186,  186,  638,  167,  168,  169,  170,  171,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  173,
      187,  187,  188,  188,  189,  189,  190,  190,  191,  191,
      192,  192,  193,  193,  194,  194,  195,  195,  196,  196,

      197,  197,  198,  198,  199,  199,  200,  200,  201,  201,
      202,  202,  203,  203,  204,  204,  205,  205,  206,  206,
      207,  207,  208,  208,  209,  209,  210,  210,  211,  211,
      212,  212,  254,  255,  256,  257,  258,  259,  260,  261,
      262,  263,  264,  265,  266,  267,  268,  269,  270,  271,
      272,  273,  274,  275,  276,  277,  278,  279,  280,  281,
      282,  283,  284,  285,  286,  287,  288,  289,  290,  291,
      292,  293,  295,  295,  637,  254,  255,  256,  257,  258,
      259,  260,  261,  262,  263,  264,  265,  266,  267,  268,
      269,  270,  271,  272,  273,  274,  275,  276,  277,  278,

      279,  280,  281,  282,  283,  284,  285,  286,  287,  288,
      289,  290,  291,  292,  293,  296,  296,  297,  297,  298,
      298,  299,  299,  300,  300,  301,  302,  302,  303,  303,
      304,  304,  305,  305,  306,  306,  307,  307,  308,  308,
      309,  309,  310,  310,  311,  312,  312,  313,  313,  314,
      314,  315,  315,  316,  316,  317,  317,  318,  318,  319,
      319,  320,  320,  321,  321,  322,  322,  323,  301,  324,
      324,  325,  325,  326,  326,  334,  334,  341,  344,  344,
      356,  356,  361,  362,  363,  364,  365,  311,  366,  368,
      369,  370,  371,  372,  373,  374,  375,  376,  341,  377,

      379,  380,  381,  382,  383,  384,  385,  386,  387,  388,
      323,  389,  391,  392,  393,  395,  395,  396,  396,  397,
      397,  398,  398,  399,  635,  361,  362,  363,  364,  365,
      407,  366,  368,  369,  370,  371,  372,  373,  374,  375,
      376,  634,  377,  379,  380,  381,  382,  383,  384,  385,
      386,  387,  388,  418,  389,  391,  392,  393,  400,  400,
      401,  401,  402,  402,  403,  403,  399,  404,  404,  405,
      405,  406,  406,  407,  408,  408,  409,  409,  410,  410,
      411,  411,  412,  412,  413,  413,  414,  414,  415,  415,
      416,  416,  417,  417,  419,  449,  418,  420,  420,  426,

      426,  434,  434,  445,  445,  446,  446,  450,  451,  452,
      454,  455,  456,  457,  458,  459,  460,  462,  463,  464,
      465,  466,  467,  468,  469,  470,  471,  474,  476,  477,
      477,  478,  479,  479,  480,  480,  482,  419,  449,  481,
      481,  483,  483,  484,  484,  485,  485,  486,  486,  491,
      450,  451,  452,  454,  455,  456,  457,  458,  459,  460,
      462,  463,  464,  465,  466,  467,  468,  469,  470,  471,
      474,  476,  487,  487,  478,  488,  488,  489,  489,  482,
      490,  490,  492,  493,  493,  495,  495,  497,  497,  501,
      501,  515,  491,  510,  510,  511,  511,  517,  518,  519,

      521,  522,  523,  524,  525,  526,  527,  528,  531,  533,
      534,  534,  535,  536,  536,  537,  537,  538,  538,  539,
      540,  540,  541,  541,  543,  492,  542,  542,  544,  546,
      546,  548,  548,  560,  515,  552,  552,  556,  556,  562,
      517,  518,  519,  521,  522,  523,  524,  525,  526,  527,
      528,  531,  533,  557,  557,  535,  563,  564,  566,  567,
      568,  572,  539,  573,  574,  575,  575,  543,  576,  576,
      577,  544,  578,  579,  579,  580,  560,  581,  583,  583,
      584,  584,  562,  587,  587,  589,  589,  590,  590,  594,
      595,  597,  601,  602,  603,  603,  595,  605,  606,  563,

      564,  566,  567,  568,  572,  607,  573,  574,  609,  609,
      612,  612,  617,  577,  623,  578,  613,  613,  580,  625,
      581,  614,  614,  624,  624,  626,  627,  629,  629,  631,
      631,  636,  594,  641,  597,  601,  602,  632,  632,  595,
      605,  606,  633,  633,  642,  643,  644,  650,  607,  646,
      646,  647,  647,  651,  656,  617,  657,  623,  652,  652,
      653,  653,  625,  658,  658,  660,  630,  628,  626,  627,
      622,  621,  620,  619,  636,  616,  641,  615,  611,  610,
      608,  600,  599,  598,  596,  593,  592,  642,  643,  644,
      650,  591,  588,  586,  585,  582,  651,  656,  571,  657,

      570,  569,  565,  561,  559,  558,  555,  554,  660,  662,
      662,  662,  662,  662,  663,  663,  663,  663,  663,  664,
      664,  664,  664,  664,  665,  553,  665,  665,  665,  666,
      666,  667,  667,  669,  669,  551,  669,  669,  550,  549,
      547,  545,  532,  530,  529,  520,  516,  514,  513,  512,
      509,  508,  507,  506,  505,  504,  503,  502,  500,  499,
      498,  496,  494,  475,  473,  472,  461,  453,  448,  447,
      444,  443,  442,  441,  440,  439,  438,  437,  436,  435,
      433,  432,  431,  430,  429,  428,  427,  425,  424,  423,
      422,  421,  394,  390,  378,  367,  360,  359,  358,  357,

      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  343,  342,  340,  339,  338,  337,  336,  335,  333,
      332,  331,  330,  329,  328,  327,  294,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  236,  235,  234,  233,  232,  231,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  174,  133,  131,  128,
      127,  124,  123,  121,  120,  119,  118,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  107,  106,  104,  102,
       81,   52,   49,   39,   38,   32,   31,   28,   24,   23,

       22,   20,   18,   13,   10,    7,    5,    4,    3,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661,  661,  661,  661,
      661,  661,  661,  661,  661,  661,  661
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[81] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 
    0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "blexer.l"
#line 2 "blexer.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "bparser.tab.h"

/* Indentation tracking */
#define MAX_INDENT_DEPTH 100
int indent_stack[MAX_INDENT_DEPTH];
int indent_top = 0;
int pending_dedents = 0;
int pending_indent = 0;
int paren_depth = 0;

void push_indent(int level) {
    if (indent_top < MAX_INDENT_DEPTH - 1) {
        indent_stack[++indent_top] = level;
    }
}

int pop_indent() {
    if (indent_top > 0) {
        return indent_stack[indent_top--];
    }
    return 0;
}

int get_current_indent() {
    return indent_top > 0 ? indent_stack[indent_top] : 0;
}

void init_indent() {
    indent_top = 0;
    indent_stack[0] = 0;
    pending_dedents = 0;
    pending_indent = 0;
    paren_depth = 0;
}

/* Rename flex's generated scanner so we can wrap it */
#define YY_DECL int internal_yylex(void)

#line 1013 "lex.yy.c"

#line 1015 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 48 "blexer.l"


#line 1236 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 662 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1210 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 50 "blexer.l"
{
    /* Skip newlines inside parentheses/brackets */
    if (paren_depth > 0) {
        /* ignore newlines inside parens */
    } else {
        /* Look ahead: skip blank lines, count indentation of next real line */
        int c;
        int indent;

        while (1) {
            indent = 0;
            while ((c = input()) == ' ') {
                indent++;
            }
            if (c == '\t') {
                /* treat tab as 4 spaces */
                indent += 4;
                continue;
            }
            if (c == '\r') continue;
            if (c == '\n') continue;  /* blank line, try next */
            break;  /* found real content or EOF */
        }

        /* Put back the non-space character we just read */
        if (c != EOF && c != 0) {
            unput(c);
        }

        /* Compare indentation with current level */
        int current = get_current_indent();

        if (indent > current) {
            push_indent(indent);
            pending_indent = 1;
        } else if (indent < current) {
            while (indent_top > 0 && get_current_indent() > indent) {
                pop_indent();
                pending_dedents++;
            }
        }
        /* indent == current: no INDENT/DEDENT needed */

        return NEWLINE;
    }
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "blexer.l"
{ /* Skip carriage return */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 99 "blexer.l"
{ /* Skip whitespace within lines */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 101 "blexer.l"
{ paren_depth++; return LPAREN; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 102 "blexer.l"
{ paren_depth--; return RPAREN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "blexer.l"
{ paren_depth++; return LBRACKET; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 104 "blexer.l"
{ paren_depth--; return RBRACKET; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "blexer.l"
{ return COMMA; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 106 "blexer.l"
{ return COLON; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 107 "blexer.l"
{ return SEMICOLON; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 109 "blexer.l"
{ return PROGRAM_START; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 110 "blexer.l"
{ return PROGRAM_END; }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 112 "blexer.l"
{ yylval.strval = strdup(yytext); return INCLUDE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 114 "blexer.l"
{ return NUMBER_TYPE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 115 "blexer.l"
{ return DECIMAL_TYPE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 116 "blexer.l"
{ return BOOL_TYPE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 117 "blexer.l"
{ return CHAR_TYPE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 118 "blexer.l"
{ return STRING_TYPE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 120 "blexer.l"
{ return IF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 121 "blexer.l"
{ return ELSE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 122 "blexer.l"
{ return WHILE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 123 "blexer.l"
{ return FOR_RANGE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 124 "blexer.l"
{ return FROM; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 125 "blexer.l"
{ return FUNCTION; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 126 "blexer.l"
{ return BREAK; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 127 "blexer.l"
{ return CONTINUE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 128 "blexer.l"
{ return RETURN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 129 "blexer.l"
{ return PRINT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 130 "blexer.l"
{ return INPUT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 132 "blexer.l"
{ return ARRAY; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 134 "blexer.l"
{ return POW; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 135 "blexer.l"
{ return SQRT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 136 "blexer.l"
{ return FLOOR; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 137 "blexer.l"
{ return CEIL; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 138 "blexer.l"
{ return ABS; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 140 "blexer.l"
{ return PLUS; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 141 "blexer.l"
{ return PLUS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 142 "blexer.l"
{ return MINUS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 143 "blexer.l"
{ return MINUS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 144 "blexer.l"
{ return MULT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 145 "blexer.l"
{ return MULT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 146 "blexer.l"
{ return DIV; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 147 "blexer.l"
{ return DIV; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 148 "blexer.l"
{ return MOD; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 149 "blexer.l"
{ return MOD; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 150 "blexer.l"
{ return AND; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 151 "blexer.l"
{ return AND; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 152 "blexer.l"
{ return OR; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 153 "blexer.l"
{ return OR; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 154 "blexer.l"
{ return NOT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 155 "blexer.l"
{ return NOT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 156 "blexer.l"
{ return INC; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 157 "blexer.l"
{ return INC; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 158 "blexer.l"
{ return DEC; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 159 "blexer.l"
{ return DEC; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 160 "blexer.l"
{ return EQUAL; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 161 "blexer.l"
{ return NOT_EQUAL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 162 "blexer.l"
{ return GREATER_EQUAL; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 163 "blexer.l"
{ return LESS_EQUAL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 164 "blexer.l"
{ return GREATER; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 165 "blexer.l"
{ return LESS; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 166 "blexer.l"
{ return ASSIGN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 167 "blexer.l"
{ return EQUAL; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 168 "blexer.l"
{ return NOT_EQUAL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 169 "blexer.l"
{ return GREATER_EQUAL; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 170 "blexer.l"
{ return LESS_EQUAL; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 171 "blexer.l"
{ return GREATER; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 172 "blexer.l"
{ return LESS; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 174 "blexer.l"
{ return BOOL_TRUE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 175 "blexer.l"
{ return BOOL_FALSE; }
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 177 "blexer.l"
{ yylval.strval = strdup(yytext); return STRING_LITERAL; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 178 "blexer.l"
{ yylval.strval = strdup(yytext); return CHAR_LITERAL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 180 "blexer.l"
{
    /* Convert Bangla digits to English and parse as float */
    char *english = strdup(yytext);
    int len = strlen(yytext);
    int pos = 0;
    for(int i = 0; i < len; ) {
        if(i + 2 < len && (unsigned char)english[i] == 0xE0 &&
           (unsigned char)english[i+1] == 0xA7 &&
           (unsigned char)english[i+2] >= 0xA6 &&
           (unsigned char)english[i+2] <= 0xAF) {
            int digit = (unsigned char)english[i+2] - 0xA6;
            english[pos++] = '0' + digit;
            i += 3;
        } else {
            english[pos++] = english[i++];
        }
    }
    english[pos] = '\0';
    yylval.floatval = atof(english);
    free(english);
    return FLOAT_LITERAL;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 203 "blexer.l"
{
    /* Convert Bangla digits to English and parse as int */
    char *english = strdup(yytext);
    int len = strlen(yytext);
    int pos = 0;
    for(int i = 0; i < len; ) {
        if(i + 2 < len && (unsigned char)english[i] == 0xE0 &&
           (unsigned char)english[i+1] == 0xA7 &&
           (unsigned char)english[i+2] >= 0xA6 &&
           (unsigned char)english[i+2] <= 0xAF) {
            int digit = (unsigned char)english[i+2] - 0xA6;
            english[pos++] = '0' + digit;
            i += 3;
        } else {
            english[pos++] = english[i++];
        }
    }
    english[pos] = '\0';
    yylval.intval = atoi(english);
    free(english);
    return INT_LITERAL;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 226 "blexer.l"
{ BEGIN(COMMENT); }
	YY_BREAK

case 76:
YY_RULE_SETUP
#line 229 "blexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 230 "blexer.l"
{ }
	YY_BREAK

case 78:
YY_RULE_SETUP
#line 233 "blexer.l"
{ yylval.strval = strdup(yytext); return IDENTIFIER; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 235 "blexer.l"
{ fprintf(stderr, "Unknown character: %s at line %d\n", yytext, yylineno); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
#line 237 "blexer.l"
{
    /* Emit remaining dedents at end of file */
    if (pending_dedents > 0) {
        pending_dedents--;
        return DEDENT;
    }
    if (indent_top > 0) {
        pop_indent();
        return DEDENT;
    }
    yyterminate();
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 250 "blexer.l"
ECHO;
	YY_BREAK
#line 1812 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 662 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 662 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 661);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 250 "blexer.l"


/* Wrapper: emits pending INDENT/DEDENT tokens before calling the real scanner */
int yylex(void) {
    /* First drain any pending INDENT */
    if (pending_indent) {
        pending_indent = 0;
        return INDENT;
    }
    /* Then drain any pending DEDENTs */
    if (pending_dedents > 0) {
        pending_dedents--;
        return DEDENT;
    }
    /* Otherwise get the next token from flex */
    return internal_yylex();
}

